#!/usr/bin/env python3
"""
Autonomous Multi-Agent Protocol — Synchronizer & Compiler
Single source of truth compiler: merges .autonomous-dev-team.toml, agents/*.md, and skills/
into provider-specific configurations (.codex/, .claude/, .agents/, AGENTS.md).
Includes zero-friction init (blank [project] fields for repo owners) and CI consistency checks.
"""
# ==============================================================================
# ARCHITECTURAL RULE / INVARIANT:
# NEVER HARDCODE OR INJECT PROVIDER, MODEL, OR AGENT SETTINGS IN THIS FILE.
#
# sync.py is strictly an automated compiler engine, not a configuration store.
# ALL provider models, reasoning tiers, token limits, and agent specifications
# MUST reside exclusively in .autonomous-dev-team.toml.
# Never modify sync.py to tune, override, or hardcode model names or agent settings.
# ==============================================================================

import argparse
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

sys.dont_write_bytecode = True

def build_trampoline_args(target_py, argv):
    """Constructs execv args for Python trampoline, handling '-m' module rewriting."""
    if not argv or argv[0] == "-c":
        return None
    args = [target_py]
    if " -m " in argv[0]:
        parts = argv[0].split(" -m ", 1)
        args.extend(["-m", parts[1]])
        args.extend(argv[1:])
    else:
        args.extend(argv)
    return args


# Explicit Python version check at top of sync.py: Python 3.11+
if sys.version_info < (3, 11):
    candidates = [
        shutil.which("python3.11"),
        shutil.which("python3.12"),
        shutil.which("python3.13"),
        os.path.expanduser("~/.local/bin/python3.11"),
        "/opt/homebrew/bin/python3.11",
        "/usr/local/bin/python3.11",
    ]
    target_py = None
    for cand in candidates:
        if cand and os.path.isfile(cand) and os.access(cand, os.X_OK):
            target_py = cand
            break
    if target_py and os.path.realpath(target_py) != os.path.realpath(sys.executable):
        args = build_trampoline_args(target_py, sys.argv)
        if args is not None:
            os.execv(target_py, args)
    sys.stderr.write(
        f"Error: Python 3.11 or higher is required (found Python {sys.version_info[0]}.{sys.version_info[1]}).\n"
    )
    sys.exit(1)

CONFIG_NAME = ".autonomous-dev-team.toml"
CLIENT_CONFIG_NAME = "config.toml"
SCHEMA_NAME = "autonomous-dev-team"
SCHEMA_VERSION = 2
MANIFEST_NAME = ".autonomous-dev-team.manifest.json"
CLIENT_MANIFEST_NAME = "manifest.json"
ENCAPSULATED_DIR_NAME = ".autonomous-dev-team"
INTERNAL_DIR_NAME = "_internal"
ORCHESTRATOR_PROTOCOL = Path("agents/orchestrator.md")
import tomllib

MAX_AMBIENT_CHARS = 1600
MAX_AMBIENT_TOKENS = 400
MAX_ROLE_CHARS = 1800
MAX_ROLE_TOKENS = 450
MAX_STARTUP_CHARS = 3600
MAX_STARTUP_TOKENS = 900

LEAKAGE_MARKERS = [
    "Tier 0",
    "Tier 1",
    "Adaptive routing",
    "/root is strictly",
    "Strict orchestration invariants",
]

AUTO_GEN_HEADER_TOML = """# ==============================================================================
# AUTO-GENERATED BY sync.py FROM .autonomous-dev-team.toml AND agents/*.md
# DO NOT EDIT DIRECTLY. MAKE CHANGES IN .autonomous-dev-team.toml OR agents/ THEN RUN ./sync.py
# ==============================================================================
"""

AUTO_GEN_HEADER_MD = """<!--
==============================================================================
AUTO-GENERATED BY sync.py FROM .autonomous-dev-team.toml AND agents/*.md
DO NOT EDIT DIRECTLY. MAKE CHANGES IN .autonomous-dev-team.toml OR agents/ THEN RUN ./sync.py
==============================================================================
-->
"""

def resolve_base_dir(dir_arg: str | Path | None = None) -> Path:
    """Resolves base directory. If inside .autonomous-dev-team, resolves to parent project root."""
    if dir_arg:
        p = Path(dir_arg).resolve()
        if p.name == INTERNAL_DIR_NAME and p.parent.name == ENCAPSULATED_DIR_NAME:
            return p.parent.parent
        if p.name == ENCAPSULATED_DIR_NAME:
            return p.parent
        return p
    script_parent = Path(__file__).resolve().parent
    if script_parent.name == INTERNAL_DIR_NAME and script_parent.parent.name == ENCAPSULATED_DIR_NAME:
        return script_parent.parent.parent
    if script_parent.name == ENCAPSULATED_DIR_NAME:
        return script_parent.parent
    return script_parent


def resolve_agents_dir(base_dir: Path) -> Path:
    nested_internal = base_dir / ENCAPSULATED_DIR_NAME / INTERNAL_DIR_NAME / "agents"
    if nested_internal.is_dir():
        return nested_internal
    nested = base_dir / ENCAPSULATED_DIR_NAME / "agents"
    if nested.is_dir():
        return nested
    return base_dir / "agents"


def resolve_skills_dir(base_dir: Path) -> Path:
    nested_internal = base_dir / ENCAPSULATED_DIR_NAME / INTERNAL_DIR_NAME / "skills"
    if nested_internal.is_dir():
        return nested_internal
    nested = base_dir / ENCAPSULATED_DIR_NAME / "skills"
    if nested.is_dir():
        return nested
    return base_dir / "skills"


def resolve_manifest_path(base_dir: Path) -> Path:
    nested = base_dir / ENCAPSULATED_DIR_NAME
    if nested.is_dir():
        return nested / CLIENT_MANIFEST_NAME
    return base_dir / MANIFEST_NAME


def is_self_repo(path: Path) -> bool:
    return (
        (path / "sync.py").is_file()
        and (path / "install.py").is_file()
        and (path / "tests" / "test_sync.py").is_file()
    )


def read_canonical_source(base_dir: Path, relative_path: Path) -> str:
    candidates = []
    if relative_path == Path(CONFIG_NAME):
        candidates.append(base_dir / ENCAPSULATED_DIR_NAME / CLIENT_CONFIG_NAME)
    candidates.append(base_dir / ENCAPSULATED_DIR_NAME / INTERNAL_DIR_NAME / relative_path)
    candidates.append(base_dir / ENCAPSULATED_DIR_NAME / relative_path)
    candidates.append(base_dir / relative_path)
    for p in candidates:
        if p.is_file():
            return p.read_text(encoding="utf-8")
    raise FileNotFoundError(f"Required canonical source is missing: {base_dir / relative_path}")


def compile_orchestrator_protocol(base_dir: Path, project: dict, guardrails_block: str,
                                   provider: str = "all") -> str:
    source = read_canonical_source(base_dir, ORCHESTRATOR_PROTOCOL)
    return interpolate_prompt(source, project, guardrails_block, provider=provider).strip()


def resolve_provider(provider: str) -> str:
    return "antigravity" if provider == "agy" else provider


def resolve_reasoning_for_provider(provider: str, model: str, reasoning_effort: str) -> str:
    return reasoning_effort


def provider_agents(config: dict, provider: str) -> dict:
    """Resolve configured agents dynamically from Schema v2 models and agents tables."""
    prov = resolve_provider(provider)
    models_cfg = config.get("models", {})
    raw_agents = config.get("agents", {})
    resolved = {}
    for role, agent_cfg in raw_agents.items():
        tier = agent_cfg.get("tier", "balanced")
        reasoning_effort = agent_cfg.get("reasoning_effort", "medium")
        model = agent_cfg.get("model") or models_cfg.get(tier, {}).get(prov, "inherit")
        effort = resolve_reasoning_for_provider(prov, model, reasoning_effort)

        agent_dict = dict(agent_cfg)
        agent_dict["model"] = model
        agent_dict["tier"] = tier
        agent_dict["reasoning_effort"] = reasoning_effort
        if prov == "claude":
            agent_dict["thinking"] = effort
        elif prov in ("antigravity", "agy"):
            agent_dict["reasoning"] = effort
        resolved[role] = agent_dict
    return resolved


def resolve_orchestrator(config: dict, provider: str) -> dict:
    """Resolve orchestrator settings dynamically from Schema v2."""
    prov = resolve_provider(provider)
    models_cfg = config.get("models", {})
    orch_cfg = config.get("orchestrator", {})
    tier = orch_cfg.get("tier", "balanced")
    reasoning_effort = orch_cfg.get("reasoning_effort", "low")
    model = orch_cfg.get("model") or models_cfg.get(tier, {}).get(prov, "inherit")
    effort = resolve_reasoning_for_provider(prov, model, reasoning_effort)

    orch = dict(orch_cfg)
    orch["model"] = model
    orch["tier"] = tier
    orch["reasoning_effort"] = reasoning_effort
    if prov == "claude":
        orch["thinking"] = effort
    elif prov in ("antigravity", "agy"):
        orch["reasoning"] = effort
    return orch


def resolve_escalation_ladders(config: dict, provider: str) -> dict:
    """Return role -> [(tier, model), ...] starting at the role's base tier, from [agents.<role>].escalation."""
    prov = resolve_provider(provider)
    models_cfg = config.get("models", {})
    agents = provider_agents(config, prov)
    ladders = {}
    for role, agent_cfg in config.get("agents", {}).items():
        escalation = agent_cfg.get("escalation") or []
        if not escalation:
            continue
        steps = [(agents[role]["tier"], agents[role]["model"])]
        for tier in escalation:
            steps.append((tier, models_cfg.get(tier, {}).get(prov, "inherit")))
        ladders[role] = steps
    return ladders


def resolve_adaptive_steps(config: dict, provider: str) -> dict:
    """Resolve declared steps, collapsing changes the provider cannot deliver."""
    prov = resolve_provider(provider)
    delivery = config.get("reasoning_policy", {}).get("providers", {}).get(prov, {}).get("effort_delivery", "unsupported")
    result = {}
    for role, agent in config.get("agents", {}).items():
        if "adaptive_steps" not in agent:
            continue
        steps = []
        previous = None
        for step in agent["adaptive_steps"]:
            model = config["models"][step["tier"]].get(prov, "inherit")
            effective = (model, step["effort"] if delivery == "native" else None)
            if effective == previous:
                continue
            steps.append(dict(step, model=model, delivery=delivery))
            previous = effective
        result[role] = steps
    return result


def effort_delivery(config: dict, provider: str) -> str:
    """Describe declared delivery without inventing a provider capability."""
    return config.get("reasoning_policy", {}).get("providers", {}).get(resolve_provider(provider), {}).get("effort_delivery", "unsupported")


def render_escalation_ladder(config: dict, provider: str) -> str:
    """Render the provider-specific escalation ladder for root orchestrator adapters."""
    ladders = resolve_escalation_ladders(config, provider)
    if not ladders and not resolve_adaptive_steps(config, provider):
        return ""
    lines = [
        "## Model escalation ladder",
        "",
        "Dispatch each role on its first step. Move one step up only under the adaptive model escalation rules; record the reason in the dispatch and completion report.",
        "",
    ]
    for role, steps in ladders.items():
        if role in resolve_adaptive_steps(config, provider):
            continue
        chain = " -> ".join(f"`{tier}` (`{model}`)" for tier, model in steps)
        lines.append(f"- `{role}`: {chain}")
    for role, steps in resolve_adaptive_steps(config, provider).items():
        chain = " -> ".join(f"`{s['tier']}` (`{s['model']}`, effort `{s['effort']}`{', exceptional' if s.get('exceptional') else ''})" for s in steps)
        delivery = steps[0]["delivery"]
        lines.append(f"- `{role}`: {chain}. Effort delivery: {delivery}; ineffective steps collapsed.")
        if delivery == "native":
            lines.append("Pass model AND reasoning_effort runtime overrides when supported; otherwise report the unsupported override, never claim enforcement.")
        else:
            lines.append("Effort is advisory or unsupported; no native reasoning override is enforced.")
    if resolve_adaptive_steps(config, provider):
        lines.append(f"Reset unrelated slices; max {config['reasoning_policy']['max_repairs']} total repair attempts across all steps. Exceptional steps require prior-step failure evidence.")
    return "\n".join(lines)


def validate_model_tiers(cfg: dict) -> list:
    """Return configuration errors for tier references missing from [models]."""
    models_cfg = cfg.get("models", {})
    errors = []
    policy = cfg.get("reasoning_policy", {})
    if not isinstance(policy, dict):
        return ["reasoning_policy must be a table"]
    refs = [("orchestrator", cfg.get("orchestrator", {}).get("tier"))]
    for role, agent_cfg in cfg.get("agents", {}).items():
        refs.append((f"agents.{role}", agent_cfg.get("tier")))
        steps = agent_cfg.get("adaptive_steps")
        if steps is not None:
            if not isinstance(steps, list) or not steps:
                errors.append(f"agents.{role}.adaptive_steps must be a nonempty list")
            else:
                seen = set()
                for index, step in enumerate(steps):
                    if not isinstance(step, dict):
                        errors.append(f"agents.{role}.adaptive_steps entries must be tables")
                        continue
                    refs.append((f"agents.{role}.adaptive_steps", step.get("tier")))
                    if not isinstance(step.get("tier"), str):
                        errors.append(f"agents.{role}.adaptive_steps requires tier")
                    efforts = policy.get("efforts", [])
                    if not isinstance(efforts, list) or not isinstance(step.get("effort"), str) or step.get("effort") not in efforts:
                        errors.append(f"agents.{role}.adaptive_steps has invalid effort")
                    if not isinstance(step.get("exceptional", False), bool):
                        errors.append(f"agents.{role}.adaptive_steps exceptional must be boolean")
                    if step.get("exceptional") and index != len(steps) - 1:
                        errors.append(f"agents.{role}.adaptive_steps exceptional step must be last")
                    if isinstance(step.get("tier"), str) and isinstance(step.get("effort"), str):
                        key = (step["tier"], step["effort"])
                        if key in seen:
                            errors.append(f"agents.{role}.adaptive_steps contains duplicate step")
                        seen.add(key)
                if isinstance(steps[0], dict) and (steps[0].get("tier") != agent_cfg.get("tier") or steps[0].get("effort") != agent_cfg.get("reasoning_effort") or steps[0].get("exceptional", False)):
                    errors.append(f"agents.{role}.adaptive_steps must start at the configured tier and effort")
        escalation = agent_cfg.get("escalation", [])
        if not isinstance(escalation, list):
            errors.append(f"agents.{role}.escalation must be a list of tier names")
            continue
        refs.extend((f"agents.{role}.escalation", tier) for tier in escalation)
    for where, tier in refs:
        if tier is not None and (not isinstance(tier, str) or tier not in models_cfg):
            errors.append(f"{where} references unknown model tier '{tier}' (defined: {', '.join(models_cfg) or 'none'})")
    policy = cfg.get("reasoning_policy")
    if policy is not None:
        if not isinstance(policy, dict):
            return errors + ["reasoning_policy must be a table"]
        if not isinstance(policy.get("max_repairs"), int) or isinstance(policy.get("max_repairs"), bool) or policy["max_repairs"] < 1:
            errors.append("reasoning_policy.max_repairs must be a positive integer")
        efforts = policy.get("efforts")
        if not isinstance(efforts, list) or not efforts or any(not isinstance(e, str) or not e for e in efforts):
            errors.append("reasoning_policy.efforts must be a nonempty list of strings")
        providers = policy.get("providers", {})
        if not isinstance(providers, dict):
            return errors + ["reasoning_policy.providers must be a table"]
        for prov, capability in providers.items():
            if not isinstance(capability, dict) or capability.get("effort_delivery") not in ("native", "advisory", "unsupported"):
                errors.append(f"reasoning_policy.providers.{prov} has invalid effort_delivery")
    return errors


def load_config(config_path: Path) -> dict:
    if not config_path.exists():
        sys.exit(f"Error: Configuration file '{config_path}' not found.\nRun './sync.py --init' to generate one.")
    with open(config_path, "rb") as f:
        cfg = tomllib.load(f)
    if cfg.get("schema_version") != 2:
        sys.exit("Error: Config schema v1 is unsupported. Update to schema_version = 2.")
    tier_errors = validate_model_tiers(cfg)
    if tier_errors:
        sys.exit("Error: Invalid model tier configuration:\n  - " + "\n  - ".join(tier_errors))
    return cfg

def resolve_config_path(base_dir: Path) -> Path:
    candidates = [
        base_dir / ENCAPSULATED_DIR_NAME / CLIENT_CONFIG_NAME,
        base_dir / ENCAPSULATED_DIR_NAME / CONFIG_NAME,
        base_dir / CONFIG_NAME,
    ]
    for candidate in candidates:
        if candidate.is_file():
            return candidate
    preferred = candidates[0] if (base_dir / ENCAPSULATED_DIR_NAME).is_dir() else candidates[2]
    sys.exit(f"Error: Configuration file '{preferred}' not found.\nRun './sync.py --init' to generate one.")

def managed_path(base_dir: Path, relative: str):
    """Return a lexical in-project path only when no path component is a symlink."""
    entry = Path(relative)
    if entry.is_absolute() or ".." in entry.parts:
        return None
    root = base_dir.absolute()
    candidate = (root / entry).absolute()
    try:
        relative_candidate = candidate.relative_to(root)
    except ValueError:
        return None
    cursor = root
    for part in relative_candidate.parts:
        cursor = cursor / part
        if cursor.is_symlink():
            return None
    return candidate

def provider_scope(base_dir: Path, provider_override: str = None) -> str:
    provider = provider_override or load_config(resolve_config_path(base_dir)).get("active_provider", "all")
    return "antigravity" if provider == "agy" else provider

def output_provider(relative: str):
    path = Path(relative)
    if path.parts and path.parts[0] == ".codex":
        return "codex"
    if relative == "CLAUDE.md" or (path.parts and path.parts[0] == ".claude"):
        return "claude"
    if relative == "AGENTS.md":
        return "shared"
    if path.parts and path.parts[0] == ".agents":
        return "antigravity"
    return None

def provider_matches_scope(file_provider: str, scope: str) -> bool:
    norm_scope = "antigravity" if scope == "agy" else scope
    if norm_scope == "all":
        return True
    if file_provider == "shared":
        return norm_scope in ("claude", "antigravity")
    return file_provider == norm_scope

PROVIDER_GENERATED_PATHS = [".codex/**", ".claude/**", ".agents/**"]

def get_effective_forbidden_paths(project: dict) -> list[str]:
    """Returns forbidden paths ensuring engine-generated provider directories are always included."""
    configured = list(project.get("forbidden_paths", []))
    for p in PROVIDER_GENERATED_PATHS:
        if p not in configured:
            configured.append(p)
    return configured

def project_command(project: dict, key: str) -> str:
    """Returns a configured [project] command, or a short visible marker when the repo owner has not set it."""
    return project.get(key) or f"UNSET ({key})"

def build_project_guardrails(project: dict) -> str:
    lines = []

    subsystems = project.get("subsystems", [])
    if subsystems:
        sub_desc = ", ".join([f"`{s['name']}` ({s.get('path', '')} — {s.get('stack', '')})" for s in subsystems])
        lines.append(f"- **Subsystem Boundaries**: {sub_desc}")
        lines.append("  * *Isolation Rule*: Never combine disjoint subsystems in one implementation slice.")

    forbidden = get_effective_forbidden_paths(project)
    if forbidden:
        forb_desc = ", ".join([f"`{p}`" for p in forbidden])
        lines.append(f"- **Forbidden Build/Generated Paths**: {forb_desc}")
        lines.append("  * *Rule*: Strictly forbidden from manually editing, copying, diffing, or staging these paths.")

    focused_test = project_command(project, "focused_test_cmd")
    lines.append(f"- **Focused Unit Verification**: `{focused_test}` (Implementer must execute narrow tests to green before handoff).")

    full_test = project_command(project, "full_test_cmd")
    lines.append(f"- **Validation Suite**: `{full_test}` (Independent broader verification owned by verifier).")

    build_cmd = project_command(project, "build_cmd")
    lines.append(f"- **Build / Package Verification**: `{build_cmd}` (Owned by verifier).")

    return "\n".join(lines)

def interpolate_prompt(template_text: str, project: dict, guardrails_block: str,
                       provider: str = "all") -> str:
    forbidden = get_effective_forbidden_paths(project)
    forbidden_list = ", ".join([f"`{p}`" for p in forbidden]) if forbidden else "None"
    forbidden_globs = " ".join([f"--glob '!{p}'" for p in forbidden]) if forbidden else ""

    subsystems = project.get("subsystems", [])
    if subsystems:
        sub_names = " vs ".join([s["name"] for s in subsystems])
        sub_rule = f"Never combine {sub_names} in a single implementation slice unless verifying an explicit cross-stack contract test."
    else:
        sub_names = "different subsystems"
        sub_rule = "Respect boundaries across distinct subsystems."

    _provider = "antigravity" if provider == "agy" else provider
    if _provider == "claude":
        role_rules_path = ".claude/agents/<role>.md"
    elif _provider == "codex":
        role_rules_path = ".codex/agents/<role>.toml"
    else:
        role_rules_path = ".agents/agents/<role>/agent.md"

    replacements = {
        "{PROJECT_NAME}": project.get("name", "Project"),
        "{PROJECT_DESCRIPTION}": project.get("description", ""),
        "{PROJECT_GUARDRAILS}": guardrails_block,
        "{FORBIDDEN_PATHS_LIST}": forbidden_list,
        "{FORBIDDEN_PATHS_GLOB}": forbidden_globs,
        "{FOCUSED_TEST_CMD}": project_command(project, "focused_test_cmd"),
        "{FULL_TEST_CMD}": project_command(project, "full_test_cmd"),
        "{BUILD_CMD}": project_command(project, "build_cmd"),
        "{SUBSYSTEMS_RULE}": sub_rule,
        "{SUBSYSTEMS_LIST}": sub_names,
        "{ROLE_RULES_PATH}": role_rules_path,
    }

    text = template_text
    for placeholder, val in replacements.items():
        text = text.replace(placeholder, val)
    return text

def compile_codex(config: dict, project: dict, guardrails_block: str, base_dir: Path, agents_dir: Path) -> dict:
    """Compiles Codex configuration into .codex/config.toml and .codex/agents/*.toml. Returns map of file paths to contents."""
    orch = resolve_orchestrator(config, "codex")
    agents_conf = provider_agents(config, "codex")
    
    outputs = {}
    codex_dir = base_dir / ".codex"
    out_agents_dir = codex_dir / "agents"
    
    protocol = compile_orchestrator_protocol(base_dir, project, guardrails_block, provider="codex")
    dev_instructions = f"""# Codex delegation adapter
MANDATORY MULTI-AGENT INSTRUCTION:
The user and repository protocol explicitly ask for sub-agents, delegation, and parallel agent work for all non-trivial tasks.
- For Tier 2 (features/fixes) and Tier 3 (architecture/refactors/plans), /root MUST call `spawn_agent` to delegate work to the designated role (`architect`, `implementer`, `verifier`).
- /root is strictly an orchestrator and MUST NOT directly write multi-file implementation code or author tests.
- Use `spawn_agent` with `fork_turns = "none"` and pass only the Compact Dispatch Contract.
- Use `architect` for targeted repository discovery and planning.

{protocol}
"""
    codex_ladder = render_escalation_ladder(config, "codex")
    if codex_ladder:
        dev_instructions += (
            f"\n{codex_ladder}\n\n"
            "Use supported `spawn_agent` model and reasoning_effort overrides for each step; report unsupported controls.\n"
        )

    config_lines = [
        AUTO_GEN_HEADER_TOML,
        "# Root Orchestrator configuration",
        f'model = "{orch.get("model", "gpt-6.1-sol")}"',
        f'model_reasoning_effort = "{orch.get("reasoning_effort", "low")}"',
        f'plan_mode_reasoning_effort = "{orch.get("plan_mode_reasoning_effort", "medium")}"',
        f'tool_output_token_limit = {orch.get("tool_output_token_limit", 6000)}',
        f'model_auto_compact_token_limit = {orch.get("model_auto_compact_token_limit", 45000)}',
        f'model_auto_compact_token_limit_scope = "{orch.get("model_auto_compact_token_limit_scope", "body_after_prefix")}"',
        "",
        'developer_instructions = """',
        dev_instructions.strip(),
        '"""',
        "",
        "[features]",
        "multi_agent = true",
        ""
    ]
    
    agent_files = sorted(list(agents_dir.glob("*.md")))
    for afile in agent_files:
        if afile.name == ORCHESTRATOR_PROTOCOL.name:
            continue
        agent_name = afile.stem
        a_conf = agents_conf.get(agent_name, {})
        desc = a_conf.get("description", f"Agent: {agent_name}")
        model = a_conf.get("model", "gpt-6-luna")
        reasoning = a_conf.get("reasoning_effort", "low")
        
        config_lines.append(f"[agents.{agent_name}]")
        config_lines.append(f'description = "{desc}"')
        config_lines.append(f'config_file = "agents/{agent_name}.toml"\n')
        
        with open(afile, "r", encoding="utf-8") as f:
            template_text = f.read()
        compiled_instructions = interpolate_prompt(template_text, project, "")
        
        agent_toml_lines = [
            AUTO_GEN_HEADER_TOML,
            f'name = "{agent_name}"',
            f'description = "{desc}"',
            f'model = "{model}"',
            f'model_reasoning_effort = "{reasoning}"',
            'developer_instructions = """',
            compiled_instructions.strip(),
            '"""\n'
        ]
        
        outputs[out_agents_dir / f"{agent_name}.toml"] = "\n".join(agent_toml_lines)
        
    outputs[codex_dir / "config.toml"] = "\n".join(config_lines)
    return outputs

def compile_claude(config: dict, project: dict, guardrails_block: str,
                   base_dir: Path, agents_dir: Path) -> dict:
    """Compiles Claude Code configuration into .claude/agents/*.md. Returns map of file paths to contents."""
    agents = provider_agents(config, "claude")
    outputs = {}

    for agent_path in sorted(agents_dir.glob("*.md")):
        role = agent_path.stem
        if role == "orchestrator":
            continue
        if role not in agents:
            continue
        model = agents[role].get("model", "inherit")
        effort = agents[role].get("thinking", "medium")
        description = (
            f"{role} agent for {config['project']['name']} "
            f"(reasoning effort: {effort}; {effort_delivery(config, 'claude')})."
        )
        outputs[base_dir / f".claude/agents/{role}.md"] = (
            f"---\nname: {role}\ndescription: {description}\nmodel: {model}\n---\n\n"
            f"{AUTO_GEN_HEADER_MD}\n"
            + interpolate_prompt(
                agent_path.read_text(encoding="utf-8"), project, ""
            )
        )

    # Root orchestrator compilation
    orch_conf = resolve_orchestrator(config, "claude")
    orch_model = orch_conf.get("model", "claude-3-7-sonnet")
    orch_effort = orch_conf.get("thinking", "low")
    orch_desc = f"Root orchestrator agent for {project.get('name', 'project')} (reasoning effort: {orch_effort}; {effort_delivery(config, 'claude')})."

    protocol = compile_orchestrator_protocol(base_dir, project, guardrails_block, provider="claude")

    claude_routing = "\n".join(
        f"- `{name}`: `{agent.get('model', 'inherit')}` "
        f"(thinking: `{agent.get('thinking', 'medium')}`; {effort_delivery(config, 'claude')})"
        for name, agent in agents.items()
    )

    orch_content = f"""---
name: orchestrator
description: {orch_desc}
model: {orch_model}
---

{AUTO_GEN_HEADER_MD}
# Claude Code Delegation Adapter

{protocol}

## Claude Subagent Guidance

Use Claude Code's native agent configuration in `.claude/agents/`.
Each generated agent file contains its canonical role instructions and model mapping.

## Claude Model Routing

{claude_routing}
"""
    claude_ladder = render_escalation_ladder(config, "claude")
    if claude_ladder:
        orch_content += (
            f"\n{claude_ladder}\n\n"
            "To escalate, re-dispatch the subagent with the next step's model as the Task `model` override.\n"
        )
    if config.get("claude", {}).get("root_file") == "CLAUDE.md":
        outputs[base_dir / "CLAUDE.md"] = orch_content
    else:
        outputs[base_dir / ".claude/agents/orchestrator.md"] = orch_content

    return outputs


def compile_antigravity(config: dict, project: dict, guardrails_block: str,
                        base_dir: Path, agents_dir: Path = None) -> dict:
    """Antigravity target: native subagents."""
    if agents_dir is None:
        agents_dir = resolve_agents_dir(base_dir)

    agents = provider_agents(config, "antigravity")
    outputs = {}
    delivery = config.get("reasoning_policy", {}).get("providers", {}).get("antigravity", {}).get("effort_delivery", "unsupported")

    for agent_path in sorted(agents_dir.glob("*.md")):
        role = agent_path.stem
        if role == "orchestrator":
            continue
        if role not in agents:
            continue
        a_conf = agents[role]
        model = a_conf.get("model", "flash")
        desc = (
            a_conf.get("description")
            or f"{role} agent for {project.get('name', 'project')}"
        ) + f" (effort {delivery})"
        compiled_instructions = interpolate_prompt(
            agent_path.read_text(encoding="utf-8"), project, ""
        )
        agent_content = f"""---
name: {role}
description: {desc}
subagent: true
mainAgent: false
model: {model}
---

{AUTO_GEN_HEADER_MD}

{compiled_instructions.strip()}
"""
        outputs[base_dir / ".agents" / "agents" / role / "agent.md"] = agent_content

    return outputs


def compile_antigravity_hooks(base_dir: Path) -> str:
    """Configures Antigravity Stop hook executing verification commands."""
    sync_cmd = "python3 sync.py --run-verify --hook"
    nested_sync = base_dir / ENCAPSULATED_DIR_NAME / "sync.py"
    if nested_sync.is_file() and not (base_dir / "sync.py").is_file():
        sync_cmd = f"python3 {ENCAPSULATED_DIR_NAME}/sync.py --run-verify --hook"

    hooks = {
        "verify-gate": {
            "Stop": [
                {
                    "type": "command",
                    "command": sync_cmd,
                    "timeout": 60,
                }
            ]
        }
    }
    return json.dumps(hooks, indent=2) + "\n"


def compile_agents_md(config: dict, project: dict, guardrails_block: str,
                      base_dir: Path) -> str:
    """Compiles slim ambient AGENTS.md with project metadata, forbidden paths, and build/test commands only."""
    sections = [AUTO_GEN_HEADER_MD]
    project_name = project.get("name", "Project")
    sections.append(f"# {project_name}")
    desc = project.get("description", "").strip()
    if desc:
        sections.append(desc)
    sections.append(f"## Repository Guardrails & Commands\n\n{guardrails_block}")
    return "\n\n".join(sections).strip() + "\n"


def compile_skills(project: dict, guardrails_block: str, base_dir: Path, skills_dir: Path, scope: str) -> dict:
    """Compile canonical skills for native discovery and explicit Codex prompts."""
    outputs = {}
    if not skills_dir.exists():
        return outputs
        
    for skill_path in skills_dir.iterdir():
        if not skill_path.is_dir():
            continue
        skill_name = skill_path.name
        
        for file_path in skill_path.rglob("*"):
            if not file_path.is_file():
                continue
            
            content = read_canonical_source(base_dir, file_path.relative_to(base_dir))
            content = interpolate_prompt(content, project, guardrails_block)
            rel_path = file_path.relative_to(skill_path)
            
            if file_path.name == "SKILL.md":
                parts = content.split("---", 2)
                if len(parts) >= 3:
                    frontmatter = f"---{parts[1]}---\n"
                    body = parts[2].lstrip()
                    content = f"{frontmatter}\n{AUTO_GEN_HEADER_MD}\n{body}"
                else:
                    content = f"{AUTO_GEN_HEADER_MD}\n{content}"
            
            if scope in ("all", "antigravity", "agy", "codex"):
                outputs[base_dir / ".agents" / "skills" / skill_name / rel_path] = content
            if scope in ("all", "claude"):
                outputs[base_dir / ".claude" / "skills" / skill_name / rel_path] = content
            if scope in ("all", "codex") and file_path.name == "SKILL.md" and rel_path == Path("SKILL.md"):
                outputs[base_dir / ".codex" / "prompts" / f"{skill_name}.md"] = content
                
    return outputs

def generate_project_config_toml(project_name: str, source_dir: Path = None, active_provider: str = "all") -> str:
    """Render the canonical config for a new repo: project name set, repo-owned [project] fields left blank."""
    base_dir = source_dir or resolve_base_dir()
    canonical = read_canonical_source(base_dir, Path(CONFIG_NAME))
    
    provider_val = "antigravity" if active_provider == "agy" else active_provider
    lines = canonical.splitlines(keepends=True)
    for i, line in enumerate(lines):
        if line.startswith("active_provider ="):
            lines[i] = f'active_provider = "{provider_val}"\n'
            break
    canonical = "".join(lines)
    
    tomllib.loads(canonical)
    values = {
        "name": project_name,
        "description": "",
        "focused_test_cmd": "",
        "full_test_cmd": "",
        "build_cmd": "",
    }
    lines = canonical.splitlines(keepends=True)
    project_start = next((i for i, line in enumerate(lines) if line.strip() == "[project]"), None)
    if project_start is None:
        raise ValueError(f"Canonical {CONFIG_NAME} is missing [project]")
    project_end = next(
        (i for i in range(project_start + 1, len(lines)) if lines[i].strip().startswith("[")),
        len(lines),
    )
    replacements = []
    for key, value in values.items():
        starts = [
            i for i in range(project_start + 1, project_end)
            if lines[i].split("=", 1)[0].strip() == key and "=" in lines[i]
        ]
        if len(starts) != 1:
            raise ValueError(f"Canonical {CONFIG_NAME} must define [project].{key} exactly once")
        start = starts[0]
        end = None
        for candidate_end in range(start + 1, project_end + 1):
            try:
                parsed = tomllib.loads("[project]\n" + "".join(lines[start:candidate_end]))
            except tomllib.TOMLDecodeError:
                continue
            if key in parsed.get("project", {}):
                end = candidate_end
                break
        if end is None:
            raise ValueError(f"Canonical {CONFIG_NAME} has an invalid [project].{key} assignment")
        replacements.append((start, end, f"{key} = {json.dumps(value, ensure_ascii=False)}\n"))
    for start, end, replacement in reversed(replacements):
        lines[start:end] = [replacement]
    rendered = "".join(lines)
    tomllib.loads(rendered)
    return rendered

def generate_all_outputs(base_dir: Path, provider_override: str = None) -> dict:
    """Generates a dict of Path -> content for all target provider files without writing them to disk."""
    config_path = resolve_config_path(base_dir)
    agents_dir = resolve_agents_dir(base_dir)
    config = load_config(config_path)
    project = dict(config.get("project", {}))
    project["forbidden_paths"] = get_effective_forbidden_paths(project)
    provider = provider_override or config.get("active_provider", "all")
    
    guardrails_block = build_project_guardrails(project)
    
    all_outputs = {}
    if provider in ("all", "claude", "antigravity", "agy"):
        all_outputs[base_dir / "AGENTS.md"] = compile_agents_md(config, project, guardrails_block, base_dir)
    if provider in ("all", "codex"):
        all_outputs.update(compile_codex(config, project, guardrails_block, base_dir, agents_dir))
    if provider in ("all", "claude"):
        all_outputs.update(compile_claude(config, project, guardrails_block, base_dir, agents_dir))
    if provider in ("all", "antigravity", "agy"):
        all_outputs.update(compile_antigravity(config, project, guardrails_block, base_dir, agents_dir))
        all_outputs[base_dir / ".agents" / "hooks.json"] = compile_antigravity_hooks(base_dir)
        
    skills_dir = resolve_skills_dir(base_dir)
    all_outputs.update(compile_skills(project, guardrails_block, base_dir, skills_dir, provider))
        
    return all_outputs

def run_sync(base_dir: Path, provider_override: str = None):
    """Synchronizes all target provider configurations, writes generated files, prunes stale artifacts, and updates the manifest."""
    print("Synchronizing Multi-Provider Autonomous Agent Protocol...")
    outputs = generate_all_outputs(base_dir, provider_override)
    manifest_path = resolve_manifest_path(base_dir)
    previous = []
    if manifest_path.exists():
        try:
            previous = json.loads(manifest_path.read_text(encoding="utf-8")).get("files", [])
        except (OSError, ValueError, TypeError):
            previous = []
    elif (base_dir / MANIFEST_NAME).exists():
        try:
            previous = json.loads((base_dir / MANIFEST_NAME).read_text(encoding="utf-8")).get("files", [])
        except (OSError, ValueError, TypeError):
            previous = []
    current = {str(path.relative_to(base_dir)) for path in outputs}
    scope = provider_scope(base_dir, provider_override)
    preserved = set() if scope == "all" else {
        path for path in previous if not provider_matches_scope(output_provider(path), scope)
    }
    for relative in sorted(set(previous) - current - preserved):
        stale = managed_path(base_dir, relative)
        if stale and stale.is_file():
            content = stale.read_text(encoding="utf-8")
            if (
                "AUTO-GENERATED BY sync.py" in content
                or (output_provider(relative) == "claude" and relative.startswith(".claude/agents/"))
                or (output_provider(relative) == "codex" and relative.startswith(".codex/agents/"))
                or (output_provider(relative) == "antigravity" and relative.startswith(".agents/agents/"))
            ):
                stale.unlink()
                try:
                    parent = stale.parent
                    if parent != base_dir and parent.is_dir() and not any(parent.iterdir()):
                        parent.rmdir()
                except OSError:
                    pass
    
    codex_agent_count = 0
    claude_agent_count = 0
    antigravity_agent_count = 0
    agents_md_updated = False
    
    for fpath, content in outputs.items():
        fpath.parent.mkdir(parents=True, exist_ok=True)
        with open(fpath, "w", encoding="utf-8") as f:
            f.write(content)
        if ".codex/agents" in fpath.as_posix():
            codex_agent_count += 1
        elif ".claude/agents" in fpath.as_posix():
            claude_agent_count += 1
        elif ".agents/agents" in fpath.as_posix() and fpath.name == "agent.md":
            antigravity_agent_count += 1
        elif fpath.name == "AGENTS.md":
            agents_md_updated = True
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(json.dumps({"schema": SCHEMA_NAME, "version": SCHEMA_VERSION,
                                         "files": sorted(current | preserved)}, indent=2) + "\n", encoding="utf-8")
    if manifest_path != (base_dir / MANIFEST_NAME) and (base_dir / MANIFEST_NAME).is_file():
        try:
            (base_dir / MANIFEST_NAME).unlink()
        except OSError:
            pass
            
    if agents_md_updated:
        print("  ✓ Universal: Generated AGENTS.md")
    if codex_agent_count > 0:
        print(f"  ✓ Codex: Compiled {codex_agent_count} agents into .codex/")
    if claude_agent_count > 0:
        print(f"  ✓ Claude Code: Compiled {claude_agent_count} agents into .claude/agents/")
    if antigravity_agent_count > 0:
        print(f"  ✓ Antigravity: Compiled {antigravity_agent_count} agents into .agents/agents/")
    
    skills_count = sum(1 for p in current if "/skills/" in str(p) or "/prompts/" in str(p))
    if skills_count > 0:
        print(f"  ✓ Skills: Compiled canonical skills to providers")

    for candidate in (
        base_dir / ENCAPSULATED_DIR_NAME / "__pycache__",
        base_dir / ENCAPSULATED_DIR_NAME / INTERNAL_DIR_NAME / "__pycache__",
    ):
        if candidate.is_dir() and not candidate.is_symlink():
            try:
                shutil.rmtree(candidate)
            except OSError:
                pass

    print("✓ Synchronization complete.\n")

def run_check(base_dir: Path, provider_override: str = None, quiet: bool = False) -> int:
    """Checks generated files and their ownership manifest. Returns 0 if matching."""
    outputs = generate_all_outputs(base_dir, provider_override)
    mismatched = []
    missing = []
    stale = []
    budget_errors = []
    leakage_errors = []
    
    for fpath, expected_content in outputs.items():
        if not fpath.exists():
            missing.append(fpath.relative_to(base_dir))
        else:
            with open(fpath, "r", encoding="utf-8") as f:
                actual_content = f.read()
            if actual_content != expected_content:
                mismatched.append(fpath.relative_to(base_dir))
    manifest_path = resolve_manifest_path(base_dir)
    if not manifest_path.exists():
        fallback = base_dir / MANIFEST_NAME
        if fallback.exists():
            manifest_path = fallback
        else:
            missing.append(manifest_path.relative_to(base_dir))
    if manifest_path.exists():
        try:
            owned = json.loads(manifest_path.read_text(encoding="utf-8")).get("files", [])
        except (OSError, ValueError, TypeError):
            owned = []
        expected = {str(path.relative_to(base_dir)) for path in outputs}
        scope = provider_scope(base_dir, provider_override)
        stale = [Path(path) for path in owned
                 if path not in expected and provider_matches_scope(output_provider(path), scope)
                 and managed_path(base_dir, path)
                 and managed_path(base_dir, path).exists()]
                
    # 1. Token Budget Enforcement
    ambient_file = base_dir / "AGENTS.md"
    ambient_content = ""
    if ambient_file.is_file():
        ambient_content = ambient_file.read_text(encoding="utf-8")
    elif ambient_file in outputs:
        ambient_content = outputs[ambient_file]

    ambient_chars = len(ambient_content)
    ambient_tokens = estimate_tokens(ambient_chars)
    if ambient_content and (ambient_chars > MAX_AMBIENT_CHARS or ambient_tokens > MAX_AMBIENT_TOKENS):
        budget_errors.append(
            f"Ambient file AGENTS.md exceeds budget: {ambient_chars} chars (~{ambient_tokens} tokens) "
            f"(limit: {MAX_AMBIENT_CHARS} chars / {MAX_AMBIENT_TOKENS} tokens)"
        )

    for fpath, expected_content in outputs.items():
        rel = fpath.relative_to(base_dir)
        is_subagent = False
        if len(rel.parts) == 4 and rel.parts[:2] == (".agents", "agents") and rel.name == "agent.md":
            if rel.parts[2] != "orchestrator":
                is_subagent = True
        elif len(rel.parts) == 3 and rel.parts[:2] == (".claude", "agents") and rel.suffix == ".md":
            if rel.stem != "orchestrator":
                is_subagent = True
        elif len(rel.parts) == 3 and rel.parts[:2] == (".codex", "agents") and rel.suffix == ".toml":
            if rel.stem != "orchestrator":
                is_subagent = True

        if is_subagent:
            actual_content = fpath.read_text(encoding="utf-8") if fpath.is_file() else expected_content
            role_chars = len(actual_content)
            role_tokens = estimate_tokens(role_chars)
            if role_chars > MAX_ROLE_CHARS or role_tokens > MAX_ROLE_TOKENS:
                budget_errors.append(
                    f"Subagent role {rel} exceeds budget: {role_chars} chars (~{role_tokens} tokens) "
                    f"(limit: {MAX_ROLE_CHARS} chars / {MAX_ROLE_TOKENS} tokens)"
                )
            start_cost_chars = ambient_chars + role_chars
            start_cost_tokens = estimate_tokens(start_cost_chars)
            if start_cost_chars > MAX_STARTUP_CHARS or start_cost_tokens > MAX_STARTUP_TOKENS:
                budget_errors.append(
                    f"Subagent startup cost for {rel} exceeds budget: {start_cost_chars} chars (~{start_cost_tokens} tokens) "
                    f"(limit: {MAX_STARTUP_CHARS} chars / {MAX_STARTUP_TOKENS} tokens)"
                )

    # 2. Data-Driven Leakage Scanner
    files_to_scan = []
    if ambient_file.is_file():
        files_to_scan.append((ambient_file, ambient_content))
    elif ambient_file in outputs:
        files_to_scan.append((ambient_file, outputs[ambient_file]))

    for fpath, expected_content in outputs.items():
        rel = fpath.relative_to(base_dir)
        is_subagent = False
        if len(rel.parts) == 4 and rel.parts[:2] == (".agents", "agents") and rel.name == "agent.md":
            if rel.parts[2] != "orchestrator":
                is_subagent = True
        elif len(rel.parts) == 3 and rel.parts[:2] == (".claude", "agents") and rel.suffix == ".md":
            if rel.stem != "orchestrator":
                is_subagent = True
        elif len(rel.parts) == 3 and rel.parts[:2] == (".codex", "agents") and rel.suffix == ".toml":
            if rel.stem != "orchestrator":
                is_subagent = True

        if is_subagent:
            actual_content = fpath.read_text(encoding="utf-8") if fpath.is_file() else expected_content
            files_to_scan.append((fpath, actual_content))

    for target_path, content in files_to_scan:
        rel_target = target_path.relative_to(base_dir)
        for marker in LEAKAGE_MARKERS:
            if marker in content:
                leakage_errors.append(f"Forbidden leakage marker '{marker}' found in {rel_target}")

    if not missing and not mismatched and not stale and not budget_errors and not leakage_errors:
        if not quiet:
            print(f"✓ All provider configurations are in sync with {CONFIG_NAME} and agents/.")
        return 0
    else:
        if not quiet:
            if missing or mismatched or stale:
                print("Error: Provider configurations are out of sync!")
                if missing:
                    print("  Missing files:")
                    for m in missing:
                        print(f"    - {m}")
                if mismatched:
                    print("  Out-of-date files:")
                    for m in mismatched:
                        print(f"    - {m}")
                if stale:
                    print("  Stale managed files:")
                    for item in stale:
                        print(f"    - {item}")
            if budget_errors:
                print("Error: Token budget exceeded!")
                for b in budget_errors:
                    print(f"    - {b}")
            if leakage_errors:
                print("Error: Orchestrator leakage detected!")
                for l in leakage_errors:
                    print(f"    - {l}")
            print("\nRun './sync.py' to regenerate provider files.")
        return 1


def run_verify(base_dir: Path, hook_mode: bool = False) -> int:
    """
    Executes the configured [project] build_cmd and full_test_cmd, skipping any left blank.
    Exits 0 if all pass, 1 if any fail.
    When hook_mode is True, formats stdout as an Antigravity Stop hook JSON response.
    """
    config_path = resolve_config_path(base_dir)
    config = load_config(config_path)
    project = config.get("project", {})
    verify_cmds = [c for c in [project.get("build_cmd", ""), project.get("full_test_cmd", "")] if c]

    all_passed = True
    for cmd in verify_cmds:
        res = subprocess.run(cmd, shell=True, cwd=str(base_dir), capture_output=hook_mode)
        if res.returncode != 0:
            all_passed = False
            break

    if hook_mode:
        if all_passed:
            print(json.dumps({"decision": "allow"}))
            return 0
        else:
            print(json.dumps({
                "decision": "continue",
                "reason": "Verification commands failed with non-zero exit code. Fix failures before stopping."
            }))
            return 0
    else:
        return 0 if all_passed else 1

PROVIDER_DISPLAY_NAMES = {
    "antigravity": "Google Antigravity",
    "agy": "Google Antigravity",
    "claude": "Claude Code",
    "codex": "Codex",
    "all": "All Providers (Codex, Claude Code, Google Antigravity)",
}

def detect_runtime_provider() -> str | None:
    """Detects runtime agent environment from environment variables."""
    if any(k in os.environ for k in ("ANTIGRAVITY_AGENT", "ANTIGRAVITY_CONVERSATION_ID", "ANTIGRAVITY_LS_ADDRESS")):
        return "antigravity"
    if any(k in os.environ for k in ("CLAUDE_CODE", "CLAUDECODE", "CLAUDE_SESSION_ID", "CLAUDE_PROJECT_DIR", "CLAUDE_CONVERSATION_ID")):
        return "claude"
    if any(k in os.environ for k in ("CODEX_CLI", "CODEX_THREAD_ID", "CODEX_SANDBOX")):
        return "codex"
    return None

def inspect_team(base_dir: Path, provider_override: str = None) -> int:
    """Inspects and prints the active provider configuration, setup sync status, and dev team roster."""
    config_path = resolve_config_path(base_dir)
    config = load_config(config_path)
    active_prov = provider_override or detect_runtime_provider() or config.get("active_provider", "all")
    if active_prov == "agy":
        active_prov = "antigravity"
    scope = active_prov

    check_code = run_check(base_dir, provider_override, quiet=True)
    status_str = "✓ In sync" if check_code == 0 else "⚠ Out of sync (run './sync.py' to update)"

    display_name = PROVIDER_DISPLAY_NAMES.get(active_prov, active_prov)
    print("==============================================================================")
    print("Autonomous Dev Team — Provider & Setup Status")
    print("==============================================================================")
    cfg_display = config_path.name
    print(f"  Configuration File : {cfg_display}")
    print(f"  Active Provider    : {display_name} (setting: {active_prov})")
    print(f"  Setup Sync Status  : {status_str}")
    print()

    target_providers = ["antigravity", "claude", "codex"] if scope == "all" else [scope]
    for prov in target_providers:
        prov_name = PROVIDER_DISPLAY_NAMES.get(prov, prov)
        agents = provider_agents(config, prov)
        orch = resolve_orchestrator(config, prov)
        orch_model = orch.get("model", "inherit")
        if prov == "claude":
            orch_effort = orch.get("thinking", "none")
        elif prov in ("antigravity", "agy"):
            orch_effort = orch.get("reasoning", "none")
        else:
            orch_effort = orch.get("reasoning_effort", "none")

        ladders = resolve_escalation_ladders(config, prov)
        adaptive = resolve_adaptive_steps(config, prov)
        delivery = config.get("reasoning_policy", {}).get("providers", {}).get(prov, {}).get("effort_delivery", "unsupported")
        rows = [("orchestrator (/root)", f"model `{orch_model}`", orch_effort, "")]
        for agent_name, agent_cfg in agents.items():
            model = agent_cfg.get("model", "inherit")
            if prov == "claude":
                effort = agent_cfg.get("thinking", orch_effort)
            elif prov in ("antigravity", "agy"):
                effort = agent_cfg.get("reasoning", orch_effort)
            else:
                effort = agent_cfg.get("reasoning_effort", orch_effort)
            escalates = ""
            if agent_name in ladders:
                escalates = "  escalates: " + " -> ".join(
                    f"{tier} `{tier_model}`" for tier, tier_model in ladders[agent_name][1:]
                )
            if agent_name in adaptive:
                escalates = "  adaptive: " + " -> ".join(
                    f"{step['tier']} `{step['model']}`/{step['effort']}" for step in adaptive[agent_name]
                ) + f" (effort {delivery}; ineffective steps collapsed)"
            rows.append((agent_name, f"model `{model}`", effort, escalates))

        max_role_len = max(len(r[0]) for r in rows)
        max_model_len = max(len(r[1]) for r in rows)

        print(f"[{prov_name} Team Roster]")
        for role, model_str, effort, escalates in rows:
            print(f"  • {role:<{max_role_len}} : {model_str:<{max_model_len}}  (reasoning: `{effort}`){escalates}")
        print()

    return check_code

def estimate_tokens(chars: int) -> int:
    """Estimates token count from characters using standard 4 characters per token."""
    return round(chars / 4)

def run_stats(base_dir: Path, provider: str = None, quiet: bool = False) -> dict:
    """
    Reports exact character and estimated token counts (standard 4 chars/token) for:
    - Ambient files (loaded into context automatically across all sessions)
    - Root orchestrator
    - Each subagent start cost (ambient + role)
    - Total active tree per provider.
    Returns a dictionary of statistics by provider, and prints a formatted report if quiet is False.
    """
    base_dir = Path(base_dir).resolve()
    config_path = resolve_config_path(base_dir)
    config = load_config(config_path)

    if provider:
        target = "antigravity" if provider == "agy" else provider
        target_providers = ["antigravity", "claude", "codex"] if target == "all" else [target]
    else:
        active = config.get("active_provider", "all")
        if active == "all":
            target_providers = ["antigravity", "claude", "codex"]
        else:
            active_norm = "antigravity" if active == "agy" else active
            target_providers = [active_norm]

    outputs = generate_all_outputs(base_dir, "all")
    stats = {}

    for prov in target_providers:
        prov_name = PROVIDER_DISPLAY_NAMES.get(prov, prov)
        prov_files = {
            p: content
            for p, content in outputs.items()
            if provider_matches_scope(output_provider(str(p.relative_to(base_dir))), prov)
        }

        # 1. Ambient files:
        ambient_files_list = []
        if prov in ("claude", "antigravity"):
            agents_md = base_dir / "AGENTS.md"
            if agents_md in prov_files:
                ambient_files_list.append((agents_md, prov_files[agents_md]))
            else:
                claude_md = base_dir / "CLAUDE.md"
                if claude_md in prov_files:
                    ambient_files_list.append((claude_md, prov_files[claude_md]))

        ambient_chars = sum(len(c) for _, c in ambient_files_list)
        ambient_tokens = estimate_tokens(ambient_chars)

        # 2. Root orchestrator:
        orch_files_list = []
        if prov == "claude":
            orch_agent = base_dir / ".claude" / "agents" / "orchestrator.md"
            if orch_agent in prov_files:
                orch_files_list.append((orch_agent, prov_files[orch_agent]))
            elif (base_dir / "CLAUDE.md") in prov_files:
                orch_files_list.append((base_dir / "CLAUDE.md", prov_files[base_dir / "CLAUDE.md"]))
            else:
                orch_files_list = list(ambient_files_list)
        elif prov == "antigravity":
            orch_path = base_dir / "agents" / "orchestrator.md"
            if not orch_path.is_file():
                orch_path = base_dir / ENCAPSULATED_DIR_NAME / INTERNAL_DIR_NAME / "agents" / "orchestrator.md"
            if orch_path.is_file():
                orch_files_list.append((orch_path, orch_path.read_text(encoding="utf-8")))
            else:
                orch_files_list = list(ambient_files_list)
        elif prov == "codex":
            codex_cfg = base_dir / ".codex" / "config.toml"
            if codex_cfg in prov_files:
                orch_files_list.append((codex_cfg, prov_files[codex_cfg]))

        orch_chars = sum(len(c) for _, c in orch_files_list)
        orch_tokens = estimate_tokens(orch_chars)

        # 3. Subagents start cost (ambient + role):
        subagents = {}
        for p, content in sorted(prov_files.items(), key=lambda item: str(item[0])):
            rel = p.relative_to(base_dir)
            role_name = None
            if prov == "claude" and len(rel.parts) == 3 and rel.parts[:2] == (".claude", "agents") and rel.suffix == ".md":
                if p.stem != "orchestrator":
                    role_name = p.stem
            elif prov == "antigravity" and len(rel.parts) == 4 and rel.parts[:2] == (".agents", "agents") and rel.name == "agent.md":
                if rel.parts[2] != "orchestrator":
                    role_name = rel.parts[2]
            elif prov == "codex" and len(rel.parts) == 3 and rel.parts[:2] == (".codex", "agents") and rel.suffix == ".toml":
                if p.stem != "orchestrator":
                    role_name = p.stem

            if role_name:
                role_chars = len(content)
                role_tokens = estimate_tokens(role_chars)
                start_chars = ambient_chars + role_chars
                start_tokens = estimate_tokens(start_chars)
                subagents[role_name] = {
                    "file": str(rel),
                    "role_characters": role_chars,
                    "role_chars": role_chars,
                    "role_tokens": role_tokens,
                    "ambient_characters": ambient_chars,
                    "ambient_chars": ambient_chars,
                    "ambient_tokens": ambient_tokens,
                    "start_cost_characters": start_chars,
                    "start_cost_chars": start_chars,
                    "start_cost_tokens": start_tokens,
                }

        # 4. Total active tree:
        total_tree_chars = sum(len(c) for c in prov_files.values())
        total_tree_tokens = estimate_tokens(total_tree_chars)

        stats[prov] = {
            "provider": prov,
            "display_name": prov_name,
            "ambient": {
                "files": [
                    {
                        "path": str(fpath.relative_to(base_dir)),
                        "characters": len(cnt),
                        "chars": len(cnt),
                        "tokens": estimate_tokens(len(cnt)),
                    }
                    for fpath, cnt in ambient_files_list
                ],
                "characters": ambient_chars,
                "chars": ambient_chars,
                "tokens": ambient_tokens,
            },
            "orchestrator": {
                "files": [
                    {
                        "path": str(fpath.relative_to(base_dir)),
                        "characters": len(cnt),
                        "chars": len(cnt),
                        "tokens": estimate_tokens(len(cnt)),
                    }
                    for fpath, cnt in orch_files_list
                ],
                "characters": orch_chars,
                "chars": orch_chars,
                "tokens": orch_tokens,
            },
            "subagents": subagents,
            "total_active_tree": {
                "files_count": len(prov_files),
                "characters": total_tree_chars,
                "chars": total_tree_chars,
                "tokens": total_tree_tokens,
            },
        }

    if not quiet:
        print("==============================================================================")
        print("Autonomous Dev Team — Context & Token Statistics")
        print("==============================================================================")
        print(f"  Configuration File : {config_path.name}")
        print(f"  Token Standard     : 4 characters / token (estimate)")
        print()

        for prov in target_providers:
            p_data = stats[prov]
            prov_name = p_data["display_name"]
            amb = p_data["ambient"]
            orch = p_data["orchestrator"]
            tree = p_data["total_active_tree"]
            subs = p_data["subagents"]

            print(f"[{prov_name}]")
            print("  Ambient Files:")
            if amb["files"]:
                for af in amb["files"]:
                    print(f"    • {af['path']} : {af['chars']:,} chars (~{af['tokens']:,} tokens)")
            else:
                print("    • (none) : 0 chars (~0 tokens)")
            print(f"    Total Ambient: {amb['chars']:,} chars (~{amb['tokens']:,} tokens)")
            print()

            print("  Root Orchestrator:")
            for of in orch["files"]:
                print(f"    • {of['path']} : {of['chars']:,} chars (~{of['tokens']:,} tokens)")
            if not orch["files"]:
                print("    • (none) : 0 chars (~0 tokens)")
            print(f"    Total Root: {orch['chars']:,} chars (~{orch['tokens']:,} tokens)")
            print()

            print("  Subagent Start Costs (ambient + role):")
            if subs:
                max_name_len = max(len(name) for name in subs)
                for role_name, s_info in subs.items():
                    print(
                        f"    • {role_name:<{max_name_len}} : "
                        f"role {s_info['role_chars']:>6,} chars (~{s_info['role_tokens']:>5,} tokens) | "
                        f"start cost {s_info['start_cost_chars']:>6,} chars (~{s_info['start_cost_tokens']:>5,} tokens)"
                    )
            else:
                print("    • (none)")
            print()

            print("  Total Active Tree:")
            print(f"    • {tree['files_count']} files : {tree['chars']:,} chars (~{tree['tokens']:,} tokens)")
            print()

    return stats

def run_init(target_dir: Path, provider_override: str = None, source_dir: Path = None):
    """Initializes the configuration if missing, then compiles provider files."""
    print(f"Initializing Autonomous Multi-Agent Protocol in: {target_dir.resolve()}")

    existing_config = None
    for candidate in (
        target_dir / ENCAPSULATED_DIR_NAME / CLIENT_CONFIG_NAME,
        target_dir / ENCAPSULATED_DIR_NAME / CONFIG_NAME,
        target_dir / CONFIG_NAME,
    ):
        if candidate.is_file():
            existing_config = candidate
            break

    if existing_config:
        print(f"  ℹ Existing {existing_config.name} found in {target_dir.resolve()}. Preserving settings.")
    else:
        if is_self_repo(target_dir) or (target_dir / CONFIG_NAME).is_file():
            config_path = target_dir / CONFIG_NAME
        else:
            config_path = target_dir / ENCAPSULATED_DIR_NAME / CLIENT_CONFIG_NAME
        config_path.parent.mkdir(parents=True, exist_ok=True)

        config_content = generate_project_config_toml(
            target_dir.resolve().name, source_dir=source_dir, active_provider=provider_override or "all"
        )
        with open(config_path, "w", encoding="utf-8") as f:
            f.write(config_content)
        print(f"  ✓ Generated {config_path.name} with blank [project] fields.")
        print("    Define focused_test_cmd, full_test_cmd, and build_cmd before relying on agent verification.")

    run_sync(target_dir, provider_override)

def main():
    parser = argparse.ArgumentParser(description="Autonomous Multi-Agent Protocol — Synchronizer & Compiler")
    parser.add_argument("--init", nargs="?", const=".", default=None, metavar="DIR",
                        help="Initialize configuration with blank [project] fields in target directory (defaults to current dir) and compile.")
    parser.add_argument("--check", action="store_true",
                        help="Check whether generated provider files are in sync (exits with 0 if up-to-date, 1 if out-of-sync).")
    parser.add_argument("--team", "--status", action="store_true", dest="team",
                        help="Display the active provider configuration, setup sync status, and dev team roster.")
    parser.add_argument("--stats", action="store_true",
                        help="Display token and character stats for ambient files, orchestrator, subagents, and active trees.")
    parser.add_argument("--run-verify", action="store_true",
                        help="Execute configured verification commands and exit 0 if all pass, 1 if any fail.")
    parser.add_argument("--hook", action="store_true",
                        help="Format output as Antigravity hook JSON response.")
    parser.add_argument("--provider", choices=["all", "codex", "claude", "antigravity", "agy"], default=None,
                        help="Override active provider.")
    parser.add_argument("--dir", default=None, metavar="DIR",
                        help=f"Directory containing configuration and agents/ (defaults to script directory).")

    args = parser.parse_args()

    base_dir = resolve_base_dir(args.dir)

    if args.team:
        sys.exit(inspect_team(base_dir, args.provider))
    elif args.stats:
        run_stats(base_dir, args.provider)
        sys.exit(0)
    elif args.run_verify:
        hook_mode = args.hook
        if not hook_mode and not sys.stdin.isatty():
            try:
                stdin_data = sys.stdin.read()
                if "terminationReason" in stdin_data or "executionNum" in stdin_data:
                    hook_mode = True
            except Exception:
                pass
        sys.exit(run_verify(base_dir, hook_mode=hook_mode))
    elif args.init is not None:
        target_dir = Path(args.init).resolve()
        run_init(target_dir, args.provider, source_dir=base_dir)
    elif args.check:
        sys.exit(run_check(base_dir, args.provider))
    else:
        run_sync(base_dir, args.provider)

if __name__ == "__main__":
    main()
