#!/usr/bin/env python3
"""
Autonomous Multi-Agent Protocol — Synchronizer / Compiler
Single source of truth compiler: merges config.toml + agents/*.md into
provider-specific configurations (.codex/, CLAUDE.md, AGENTS.md).
"""

import os
import sys
from pathlib import Path

# Python 3.11+ tomllib support
try:
    import tomllib
except ImportError:
    try:
        import tomli as tomllib
    except ImportError:
        sys.exit("Error: Python 3.11+ is required for built-in tomllib (or install tomli).")

BASE_DIR = Path(__file__).resolve().parent
AGENTS_DIR = BASE_DIR / "agents"
CONFIG_PATH = BASE_DIR / "config.toml"

AUTO_GEN_HEADER_TOML = """# ==============================================================================
# AUTO-GENERATED BY sync.py FROM config.toml AND agents/*.md
# DO NOT EDIT DIRECTLY. MAKE CHANGES IN config.toml OR agents/ THEN RUN ./sync.py
# ==============================================================================
"""

AUTO_GEN_HEADER_MD = """<!--
==============================================================================
AUTO-GENERATED BY sync.py FROM config.toml AND agents/*.md
DO NOT EDIT DIRECTLY. MAKE CHANGES IN config.toml OR agents/ THEN RUN ./sync.py
==============================================================================
-->
"""

def load_config():
    if not CONFIG_PATH.exists():
        sys.exit(f"Error: {CONFIG_PATH} not found.")
    with open(CONFIG_PATH, "rb") as f:
        return tomllib.load(f)

def build_project_guardrails(project):
    lines = []
    
    subsystems = project.get("subsystems", [])
    if subsystems:
        sub_desc = ", ".join([f"`{s['name']}` ({s.get('path', '')} — {s.get('stack', '')})" for s in subsystems])
        lines.append(f"- **Subsystem Boundaries**: {sub_desc}")
        lines.append("  * *Isolation Rule*: Never combine disjoint subsystems in one implementation slice.")
    
    forbidden = project.get("forbidden_paths", [])
    if forbidden:
        forb_desc = ", ".join([f"`{p}`" for p in forbidden])
        lines.append(f"- **Forbidden Build/Generated Paths**: {forb_desc}")
        lines.append("  * *Rule*: Strictly forbidden from manually editing, copying, diffing, or staging these paths.")
        
    build_sync = project.get("build_sync_cmd")
    if build_sync:
        lines.append(f"- **Deterministic Build Sync**: `{build_sync}` (Automated build command; never spawn an agent to manually patch build artifacts).")
        
    focused_test = project.get("focused_test_cmd", "npm test -- {file}")
    lines.append(f"- **Focused Unit Verification**: `{focused_test}` (Implementer must execute narrow tests to green before handoff).")
    
    full_test = project.get("full_test_cmd")
    if full_test:
        lines.append(f"- **Validation Suite**: `{full_test}` (Independent broader verification owned by code-validator).")
        
    build_cmd = project.get("build_cmd")
    if build_cmd:
        lines.append(f"- **Build / Package Verification**: `{build_cmd}` (Owned by code-validator).")
        
    return "\n".join(lines)

def interpolate_prompt(template_text, project, guardrails_block):
    forbidden = project.get("forbidden_paths", [])
    forbidden_list = ", ".join([f"`{p}`" for p in forbidden]) if forbidden else "None"
    forbidden_globs = " ".join([f"--glob '!{p}'" for p in forbidden]) if forbidden else ""
    
    subsystems = project.get("subsystems", [])
    sub_names = " vs ".join([s["name"] for s in subsystems]) if subsystems else "different subsystems"
    sub_rule = f"Never combine {sub_names} in a single implementation slice unless verifying an explicit cross-stack contract test."
    
    replacements = {
        "{PROJECT_NAME}": project.get("name", "Project"),
        "{PROJECT_DESCRIPTION}": project.get("description", ""),
        "{PROJECT_GUARDRAILS}": guardrails_block,
        "{FORBIDDEN_PATHS_LIST}": forbidden_list,
        "{FORBIDDEN_PATHS_GLOB}": forbidden_globs,
        "{BUILD_SYNC_CMD}": project.get("build_sync_cmd", "npm run build"),
        "{FOCUSED_TEST_CMD}": project.get("focused_test_cmd", "npm test -- {file}"),
        "{FULL_TEST_CMD}": project.get("full_test_cmd", "npm test"),
        "{BUILD_CMD}": project.get("build_cmd", "npm run build"),
        "{SUBSYSTEMS_RULE}": sub_rule,
        "{SUBSYSTEMS_LIST}": sub_names,
    }
    
    text = template_text
    for placeholder, val in replacements.items():
        text = text.replace(placeholder, val)
    return text

def compile_codex(config, project, guardrails_block):
    codex_conf = config.get("codex", {})
    orch = codex_conf.get("orchestrator", {})
    agents_conf = codex_conf.get("agents", {})
    
    codex_dir = BASE_DIR / ".codex"
    agents_dir = codex_dir / "agents"
    agents_dir.mkdir(parents=True, exist_ok=True)
    
    # 1. Compile .codex/config.toml
    config_lines = [
        AUTO_GEN_HEADER_TOML,
        "# Root Orchestrator configuration",
        f'model = "{orch.get("model", "gpt-5.6-terra")}"',
        f'model_reasoning_effort = "{orch.get("reasoning_effort", "low")}"',
        f'plan_mode_reasoning_effort = "{orch.get("plan_mode_reasoning_effort", "medium")}"',
        f'default_subagent_model = "{orch.get("default_subagent_model", "gpt-5.6-luna")}"',
        f'default_subagent_reasoning_effort = "{orch.get("default_subagent_reasoning_effort", "low")}"',
        f'max_concurrent_threads_per_session = {orch.get("max_concurrent_threads_per_session", 3)}',
        f'tool_output_token_limit = {orch.get("tool_output_token_limit", 2500)}',
        f'model_auto_compact_token_limit = {orch.get("model_auto_compact_token_limit", 45000)}',
        "",
        'developer_instructions = """',
        "# Critical Token Optimization & Operational Guardrails",
        '1. ZERO FULL-HISTORY FORKS: When calling spawn_agent, you MUST ALWAYS set fork_turns = "none". Never use fork_turns = "all" or omit it. Child agents must receive only a compact dispatch contract (<= 1,500 tokens).',
        "2. NO BUSY-POLLING: Never busy-poll wait_agent or repeatedly call list_agents. When waiting for a subagent, wait for reactive notification or use a long timeout (>= 180s).",
        "3. NO MONOLITHIC SUBAGENTS: Do not reuse a subagent across multiple disparate tasks or subsystems. Subagents must own one cohesive slice and terminate upon reporting completion.",
        "4. BOUNDED INSPECTION: Limit sed -n to <= 60 lines. Limit git diff to -U3. Pipe test runs to tail -n 25.",
        '"""',
        "",
        "[features]",
        "multi_agent = true",
        ""
    ]
    
    # 2. Compile each agent toml and add entry to config.toml
    agent_files = sorted(list(AGENTS_DIR.glob("*.md")))
    for afile in agent_files:
        agent_name = afile.stem
        a_conf = agents_conf.get(agent_name, {})
        desc = a_conf.get("description", f"Specialist agent: {agent_name}")
        model = a_conf.get("model", "gpt-5.6-luna")
        reasoning = a_conf.get("reasoning_effort", "low")
        
        # Add to .codex/config.toml
        config_lines.append(f"[agents.{agent_name}]")
        config_lines.append(f'description = "{desc}"')
        config_lines.append(f'config_file = "agents/{agent_name}.toml"\n')
        
        # Compile prompt template
        with open(afile, "r", encoding="utf-8") as f:
            template_text = f.read()
        compiled_instructions = interpolate_prompt(template_text, project, guardrails_block)
        
        # Write .codex/agents/<name>.toml
        agent_toml_lines = [
            AUTO_GEN_HEADER_TOML,
            f'name = "{agent_name}"',
            f'description = "{desc}"',
            f'model = "{model}"',
            f'model_reasoning_effort = "{reasoning}"'
        ]
        if agent_name == "commit-pusher":
            agent_toml_lines.append('sandbox_mode = "workspace-write"')
            
        agent_toml_lines.append('developer_instructions = """')
        agent_toml_lines.append(compiled_instructions.strip())
        agent_toml_lines.append('"""\n')
        
        with open(agents_dir / f"{agent_name}.toml", "w", encoding="utf-8") as f:
            f.write("\n".join(agent_toml_lines))
            
    with open(codex_dir / "config.toml", "w", encoding="utf-8") as f:
        f.write("\n".join(config_lines))
        
    print(f"  ✓ Codex: Compiled {len(agent_files)} agents into .codex/")

def compile_claude(config, project, guardrails_block):
    claude_conf = config.get("claude", {})
    orch = claude_conf.get("orchestrator", {})
    agents_conf = claude_conf.get("agents", {})
    
    claude_file = BASE_DIR / "CLAUDE.md"
    
    # Model routing table for Claude
    table_lines = [
        "| Role / Specialist | Target Model | Thinking Effort | Purpose |",
        "| :--- | :--- | :--- | :--- |",
        f"| **Orchestrator (`/root`)** | `{orch.get('model', 'claude-3-7-sonnet')}` | `{orch.get('thinking', 'low')}` | Workflow coordination, routing, cohesive seam scoping |"
    ]
    for aname, aconf in sorted(agents_conf.items()):
        table_lines.append(f"| `{aname}` | `{aconf.get('model', 'claude-3-5-haiku')}` | `{aconf.get('thinking', 'none')}` | Specialist role persona |")
        
    claude_content = f"""{AUTO_GEN_HEADER_MD}
# Claude Code — Project Guidelines & Autonomous Multi-Agent Protocol

## Project Overview: {project.get('name', 'Repository')}
{project.get('description', '')}

---

## 1. Repository Invariants & Safety Guardrails
{guardrails_block}

### Output & Command Bounding Invariants:
- Limit file reads (`sed -n`) to ≤60 lines.
- Limit diff inspection to `git diff -U3` (never use large `-U` ranges).
- Pipe broad test runs or searches to `head -n 30` or `tail -n 25`.
- Never run interactive Git commands (`git add -p`, `git add -i`, `git rebase -i`).

---

## 2. Adaptive Task Routing Policy
Before executing, classify every task into one of four tiers:
- **Tier 0 (Direct Operation)**: Inspecting status, running deterministic build sync, checking small configs → execute directly without ceremony.
- **Tier 1 (Surgical Change)**: 1 file or localized edit, typo, simple helper → execute surgical edit + narrow test.
- **Tier 2 (Cohesive Feature / Localized Bug)**: 1–3 tightly coupled files in a single subsystem → implementer owns complete behavioral seam + focused unit tests.
- **Tier 3 (Cross-Subsystem / Architectural Change)**: Multi-subsystem, lifecycle changes, boundary redesign → plan cohesive slices first, implement sequentially or cleanly partitioned, validate independently.

---

## 3. Specialist Roles & Model Routing Matrix
When assuming specialist personas or delegating subtasks, adhere to the assigned models and thinking budgets:

{chr(10).join(table_lines)}

---

## 4. Contract-Oriented Cohesive Slicing
- A slice MUST own a complete behavioral contract (state manager + consumer + tests; or client + handler + types).
- NEVER micro-slice by individual functions or separate tests from code.
- Target: 1 slice for localized fixes; 2 slices for moderate features; max 3 slices for separable workstreams.
"""
    with open(claude_file, "w", encoding="utf-8") as f:
        f.write(claude_content)
    print("  ✓ Claude Code: Generated CLAUDE.md")

def compile_gemini(config, project, guardrails_block):
    gemini_conf = config.get("gemini", {})
    orch = gemini_conf.get("orchestrator", {})
    agents_conf = gemini_conf.get("agents", {})
    
    agents_file = BASE_DIR / "AGENTS.md"
    
    table_lines = [
        "| Subagent Role | Model Tier (`invoke_subagent`) | Purpose |",
        "| :--- | :--- | :--- |",
        f"| **Orchestrator (`/root`)** | `{orch.get('model', 'pro')}` | Intent interpretation, routing, cohesive seam scoping |"
    ]
    for aname, aconf in sorted(agents_conf.items()):
        table_lines.append(f"| `{aname}` | `{aconf.get('model', 'flash')}` | Specialist persona execution |")
        
    agents_content = f"""{AUTO_GEN_HEADER_MD}
# Autonomous Multi-Agent Protocol — {project.get('name', 'Repository')}

**Charter:** The `/root` Orchestrator coordinates workflow for {project.get('name', 'this repository')} ({project.get('description', '')}). `/root` owns intent interpretation, task classification, routing, cohesive slicing, synthesis, and completion decisions. Specialized agents own planning, exploration, implementation, verification, review, and Git publishing.

The primary optimization metric is:
**Total resources required to reach a correct, validated, shippable result.**
Avoid premature multi-agent ceremonies: use one capable owner by default, and spawn specialists only when they contribute new information, independent work, or independent evidence.

---

## 1. Repository Invariants & Safety Guardrails
{guardrails_block}

### Universal Operational Invariants:
- **Subsystem Isolation**: Never combine disjoint subsystems in one implementation slice.
- **Generated Assets Rule**: Never spawn an LLM agent to copy, diff, or patch generated build assets. Use deterministic build commands (`{project.get('build_sync_cmd', 'npm run build')}`).
- **Strictly Non-Interactive Git**: Agents must never run interactive Git commands (`git add -p`, `git add -i`, `git rebase -i`).
- **Zero Full-History Forks (`fork_turns = "none"`)**: Subagents must NEVER be spawned with full parent history. Child subagents receive only the Compact Dispatch Contract (≤ 1,500 tokens).
- **Anti-Polling Invariant**: Never busy-poll or loop waiting for agents; rely on reactive wakeups or long timeouts (≥ 180s).
- **Command Output Bounds**: Limit file reads (`sed -n`) to ≤60 lines. Limit `git diff` to `-U3`. Pipe broad test outputs to `tail -n 25`.
- **Circuit Breakers**:
  * *Implementer Failure Breaker:* Stop immediately after 2 failed attempts on the same issue; report blocker to `/root`.
  * *Tool-Loop Ceilings:*
    - `/root` Orchestrator: hard ceiling of 25 turns per task.
    - Standard agents (`explorer`, `implementer`): soft warning at 10–12 tool calls, hard ceiling at 16–20.
    - Mechanical (`quick-implementer`): hard ceiling at 8.
    - Publishing (`commit-pusher`): hard maximum of 6 tool calls.

---

## 2. Adaptive Task Routing

`/root` classifies each incoming request into one of four tiers:

```
                                 TASK INTAKE
                                      │
          ┌───────────────────────────┼───────────────────────────┐
          ▼                           ▼                           ▼
    [ Tier 0/1 ]                 [ Tier 2 ]                  [ Tier 3 ]
  Direct / Surgical          Cohesive Feature            Cross-Subsystem
          │                           │                           │
  Direct Operation                    │                  code-explorer
         OR              Known Cause? ├── Yes ──► implementer   (targeted)
  quick-implementer                   │                │          │
  (focused check)                     └── No ──► code-explorer   planner
          │                                            │     (1–3 slices)
          │                                       implementer     │
          │                                            │     implementer(s)
          │                                     reviewer (risky)  │
          │                                            │     validator
          │                                            │     (build/integration)
          │                                            │          │
          │                                            │     reviewer (risky)
          └───────────────────────────┬───────────────────────────┘
                                      ▼
                                   COMPLETE
```

### Tier 0 — Direct Orchestrator Task
- **When:** Inspecting Git status, running asset sync, checking configs.
- **Workflow:** `/root` executes directly in workspace without subagents.

### Tier 1 — Surgical Change
- **When:** 1 file or tightly localized edit; typos, simple helpers, isolated bug fixes.
- **Workflow:** `quick-implementer` → runs focused unit check (`{project.get('focused_test_cmd', 'npm test -- {file}')}`) → complete.
- **Rules:** No planner, no explorer, no validator by default.

### Tier 2 — Cohesive Feature or Localized Bug
- **When:** 1–3 tightly coupled files in a single subsystem; bug with known reproduction.
- **Workflow:** `implementer` (owns cohesive seam + unit tests) → optional `code-reviewer` (if public contract/lifecycle changed).

### Tier 3 — Cross-Subsystem / Architectural Change
- **When:** Multiple subsystems, lifecycle/state changes, inter-service boundary redesign, high regression risk.
- **Workflow:** `code-explorer` → `planner` (1–3 cohesive slices) → `implementer(s)` → `code-validator` → optional `code-reviewer`.

---

## 3. Gemini / Antigravity Model Assignment Matrix
When invoking subagents via `invoke_subagent`, specify the corresponding model tier:

{chr(10).join(table_lines)}

---

## 4. Inter-Agent Communication Contracts

### A. Discovery Manifest (`code-explorer` → `/root` / `planner` / `implementer`)
```markdown
## Discovery Manifest
### Root Cause: <concise verified explanation>
### Relevant Files:
- `path/to/file` — symbol/function — why relevant
### Execution / Data Flow:
1. <entry / event> -> 2. <state mutation> -> 3. <consumer / render>
### Verified Facts:
- <concrete fact 1>
### Uncertainties: None | <specific detail>
### Recommended Ownership Boundary: <files that must stay in ONE implementation slice>
### Suggested Verification: <exact focused test command>
```

### B. Compact Dispatch Contract (`/root` → Subagent)
```markdown
## Assignment
**Goal:** <one sentence>
**Why:** <one or two sentences context>
**Scope:** `path/to/file-a`, `path/to/file-b`
**Relevant symbols:** `symbolA`, `symbolB`
**Verified facts:** <from explorer or previous turn>
**Constraints:** <e.g. preserve dirty worktree, subsystem isolation>
**Required behavior:** <concrete expected result>
**Verification responsibility:** `<exact command the agent must execute>`
**Do not do:** <explicit non-goals>
```

### C. Compact Completion Contract (Subagent → `/root`)
```markdown
## Completion
**Status:** PASS | FAIL | BLOCKED
**Changed:**
- `path/to/file`: <short description>
**Behavior:** <what now works>
**Verification:** `<command>` — PASS / FAIL
**Remaining risk:** None | <one concise item>
**Follow-up needed:** No | <exact next action>
```

### D. Repair Request Packet (`/root` → Original Implementer)
```markdown
## Repair Request
**Original goal:** ...
**Observed failure:** ...
**Exact evidence:** failing command, exit code, error excerpt
**Changed files from previous attempt:** `path/to/file`
**Known-good facts:** ...
**Scope:** Repair the existing implementation. Do not restart architectural exploration.
```

---

## 5. Validation & Review Policies

- **Validate New Risk, Not Re-Run Proof**: If the implementer verified focused unit tests to green, DO NOT re-run that command in `code-validator`. `code-validator` runs ONLY broader suites (`{project.get('full_test_cmd', 'npm test')}`) or builds (`{project.get('build_cmd', 'npm run build')}`).
- **Risk-Based Review**: Invoke `code-reviewer` only for semantic risk (state machine, concurrency, boundaries, security, storage migrations, public contracts). Skip for pure DOM/CSS, presentation, formatting, or low-risk mechanical changes.
"""
    with open(agents_file, "w", encoding="utf-8") as f:
        f.write(agents_content)
    print("  ✓ Gemini / Antigravity: Generated AGENTS.md")

def main():
    print("Synchronizing Multi-Provider Autonomous Agent Protocol...")
    config = load_config()
    project = config.get("project", {})
    provider = config.get("active_provider", "all")
    
    guardrails_block = build_project_guardrails(project)
    
    if provider in ("all", "codex"):
        compile_codex(config, project, guardrails_block)
    if provider in ("all", "claude"):
        compile_claude(config, project, guardrails_block)
    if provider in ("all", "gemini"):
        compile_gemini(config, project, guardrails_block)
        
    print("✓ Synchronization complete.\n")

if __name__ == "__main__":
    main()
