#!/usr/bin/env python3
"""
Autonomous Multi-Agent Protocol — Synchronizer & Compiler
Single source of truth compiler: merges .autonomous-dev-team.toml + agents/*.md into
provider-specific configurations (.codex/, CLAUDE.md, AGENTS.md, GEMINI.md).
Includes stack auto-detection, zero-friction init, and CI consistency checks.
"""

import argparse
import json
import os
import sys
from pathlib import Path

CONFIG_NAME = ".autonomous-dev-team.toml"
LEGACY_CONFIG_NAME = "config.toml"
SCHEMA_NAME = "autonomous-dev-team"
SCHEMA_VERSION = 1
MANIFEST_NAME = ".autonomous-dev-team.manifest.json"

# Python 3.11+ tomllib support
try:
    import tomllib
except ImportError:
    try:
        import tomli as tomllib
    except ImportError:
        sys.exit("Error: Python 3.11+ is required for built-in tomllib (or install tomli).")

AUTO_GEN_HEADER_TOML = """# ==============================================================================
# AUTO-GENERATED BY sync.py FROM .autonomous-dev-team.toml AND agents/*.md
# DO NOT EDIT DIRECTLY. MAKE CHANGES IN .autonomous-dev-team.toml OR agents/ THEN RUN ./sync.py
# ==============================================================================
"""

AUTO_GEN_HEADER_MD = """<!--
==============================================================================
AUTO-GENERATED BY sync.py FROM .autonomous-dev-team.toml AND agents/*.md
DO NOT EDIT DIRECTLY. MAKE CHANGES IN .autonomous-dev-team.toml OR agents/ THEN RUN ./sync.py
==============================================================================
-->
"""

ROUTING_ASCII_DIAGRAM = """```
                                 TASK INTAKE
                                      │
          ┌───────────────────────────┼───────────────────────────┐
          ▼                           ▼                           ▼
    [ Tier 0/1 ]                 [ Tier 2 ]                  [ Tier 3 ]
  Direct / Surgical          Cohesive Feature            Cross-Subsystem
          │                           │                           │
  Direct Operation                    │                  code-explorer
         OR              Known Cause? ├── Yes ──► implementer   (targeted)
  quick-implementer                   │                │          │
  (focused check)                     └── No ──► code-explorer   planner
          │                                            │     (1–3 slices)
          │                                       implementer     │
          │                                            │     implementer(s)
          │                                     reviewer (risky)  │
          │                                            │     validator
          │                                            │     (build/integration)
          │                                            │          │
          │                                            │     reviewer (risky)
          └───────────────────────────┬───────────────────────────┘
                                      ▼
                                   COMPLETE
```"""

COMMUNICATION_CONTRACTS_MD = """## Inter-Agent Communication Contracts

### A. Discovery Manifest (`code-explorer` → `/root` / `planner` / `implementer`)
```markdown
## Discovery Manifest
### Root Cause: <concise verified explanation>
### Relevant Files:
- `path/to/file` — symbol/function — why relevant
### Execution / Data Flow:
1. <entry / event> -> 2. <state mutation> -> 3. <consumer / render>
### Verified Facts:
- <concrete fact 1>
### Uncertainties: None | <specific detail>
### Recommended Ownership Boundary: <files that must stay in ONE implementation slice>
### Suggested Verification: <exact focused test command>
```

### B. Compact Dispatch Contract (`/root` → Subagent)
```markdown
## Assignment
**Goal:** <one sentence>
**Why:** <one or two sentences context>
**Scope:** `path/to/file-a`, `path/to/file-b`
**Relevant symbols:** `symbolA`, `symbolB`
**Verified facts:** <from explorer or previous turn>
**Constraints:** <e.g. preserve dirty worktree, subsystem isolation>
**Required behavior:** <concrete expected result>
**Verification responsibility:** `<exact command the agent must execute>`
**Do not do:** <explicit non-goals>
```

### C. Compact Completion Contract (Subagent → `/root`)
```markdown
## Completion
**Status:** PASS | FAIL | BLOCKED
**Changed:**
- `path/to/file`: <short description>
**Behavior:** <what now works>
**Verification:** `<command>` — PASS / FAIL
**Remaining risk:** None | <one concise item>
**Follow-up needed:** No | <exact next action>
```

### D. Repair Request Packet (`/root` → Original Implementer)
```markdown
## Repair Request
**Original goal:** ...
**Observed failure:** ...
**Exact evidence:** failing command, exit code, error excerpt
**Changed files from previous attempt:** `path/to/file`
**Known-good facts:** ...
**Scope:** Repair the existing implementation. Do not restart architectural exploration.
```"""

def load_config(config_path: Path) -> dict:
    if not config_path.exists():
        sys.exit(f"Error: Configuration file '{config_path}' not found.\nRun './sync.py --init' to generate one.")
    with open(config_path, "rb") as f:
        return tomllib.load(f)

def is_legacy_config(config: dict) -> bool:
    project = config.get("project")
    return (isinstance(project, dict)
            and project.get("build_sync_cmd") == "python3 sync.py"
            and isinstance(project.get("forbidden_paths"), list)
            and isinstance(config.get("codex", {}).get("orchestrator"), dict))

def resolve_config_path(base_dir: Path) -> Path:
    namespaced = base_dir / CONFIG_NAME
    if namespaced.exists():
        return namespaced
    legacy = base_dir / LEGACY_CONFIG_NAME
    if legacy.exists() and is_legacy_config(load_config(legacy)):
        return legacy
    sys.exit(f"Error: Configuration file '{namespaced}' not found.\nRun './sync.py --init' to generate one.")

def managed_path(base_dir: Path, relative: str):
    """Return a lexical in-project path only when no path component is a symlink."""
    entry = Path(relative)
    if entry.is_absolute() or ".." in entry.parts:
        return None
    root = base_dir.absolute()
    candidate = (root / entry).absolute()
    try:
        relative_candidate = candidate.relative_to(root)
    except ValueError:
        return None
    cursor = root
    for part in relative_candidate.parts:
        cursor = cursor / part
        if cursor.is_symlink():
            return None
    return candidate

def provider_scope(base_dir: Path, provider_override: str = None) -> str:
    provider = provider_override or load_config(resolve_config_path(base_dir)).get("active_provider", "all")
    return "antigravity" if provider == "agy" else provider

def output_provider(relative: str):
    path = Path(relative)
    if path.parts and path.parts[0] == ".codex":
        return "codex"
    if relative == "CLAUDE.md" or (path.parts and path.parts[0] == ".claude"):
        return "claude"
    if relative == "GEMINI.md" or (path.parts and path.parts[0] == ".gemini"):
        return "gemini"
    if relative == "AGENTS.md":
        return "antigravity"
    return None

def build_project_guardrails(project: dict) -> str:
    lines = []
    
    subsystems = project.get("subsystems", [])
    if subsystems:
        sub_desc = ", ".join([f"`{s['name']}` ({s.get('path', '')} — {s.get('stack', '')})" for s in subsystems])
        lines.append(f"- **Subsystem Boundaries**: {sub_desc}")
        lines.append("  * *Isolation Rule*: Never combine disjoint subsystems in one implementation slice.")
    
    forbidden = project.get("forbidden_paths", [])
    if forbidden:
        forb_desc = ", ".join([f"`{p}`" for p in forbidden])
        lines.append(f"- **Forbidden Build/Generated Paths**: {forb_desc}")
        lines.append("  * *Rule*: Strictly forbidden from manually editing, copying, diffing, or staging these paths.")
        
    build_sync = project.get("build_sync_cmd")
    if build_sync:
        lines.append(f"- **Deterministic Build Sync**: `{build_sync}` (Automated build command; never spawn an agent to manually patch build artifacts).")
        
    focused_test = project.get("focused_test_cmd", "npm test -- {file}")
    lines.append(f"- **Focused Unit Verification**: `{focused_test}` (Implementer must execute narrow tests to green before handoff).")
    
    full_test = project.get("full_test_cmd")
    if full_test:
        lines.append(f"- **Validation Suite**: `{full_test}` (Independent broader verification owned by code-validator).")
        
    build_cmd = project.get("build_cmd")
    if build_cmd:
        lines.append(f"- **Build / Package Verification**: `{build_cmd}` (Owned by code-validator).")
        
    return "\n".join(lines)

def interpolate_prompt(template_text: str, project: dict, guardrails_block: str) -> str:
    forbidden = project.get("forbidden_paths", [])
    forbidden_list = ", ".join([f"`{p}`" for p in forbidden]) if forbidden else "None"
    forbidden_globs = " ".join([f"--glob '!{p}'" for p in forbidden]) if forbidden else ""
    
    subsystems = project.get("subsystems", [])
    sub_names = " vs ".join([s["name"] for s in subsystems]) if subsystems else "different subsystems"
    sub_rule = f"Never combine {sub_names} in a single implementation slice unless verifying an explicit cross-stack contract test."
    
    replacements = {
        "{PROJECT_NAME}": project.get("name", "Project"),
        "{PROJECT_DESCRIPTION}": project.get("description", ""),
        "{PROJECT_GUARDRAILS}": guardrails_block,
        "{FORBIDDEN_PATHS_LIST}": forbidden_list,
        "{FORBIDDEN_PATHS_GLOB}": forbidden_globs,
        "{BUILD_SYNC_CMD}": project.get("build_sync_cmd", "npm run build"),
        "{FOCUSED_TEST_CMD}": project.get("focused_test_cmd", "npm test -- {file}"),
        "{FULL_TEST_CMD}": project.get("full_test_cmd", "npm test"),
        "{BUILD_CMD}": project.get("build_cmd", "npm run build"),
        "{SUBSYSTEMS_RULE}": sub_rule,
        "{SUBSYSTEMS_LIST}": sub_names,
    }
    
    text = template_text
    for placeholder, val in replacements.items():
        text = text.replace(placeholder, val)
    return text

def compile_codex(config: dict, project: dict, guardrails_block: str, base_dir: Path, agents_dir: Path) -> dict:
    """Compiles Codex configuration into .codex/config.toml and .codex/agents/*.toml. Returns map of file paths to contents."""
    codex_conf = config.get("codex", {})
    orch = codex_conf.get("orchestrator", {})
    agents_conf = codex_conf.get("agents", {})
    
    outputs = {}
    codex_dir = base_dir / ".codex"
    out_agents_dir = codex_dir / "agents"
    
    focused_test = project.get("focused_test_cmd", "npm test -- {file}")
    full_test = project.get("full_test_cmd", "npm test")
    build_cmd = project.get("build_cmd", "npm run build")

    # Developer instructions for root orchestrator in Codex
    dev_instructions = f"""# Critical Token Optimization & Operational Guardrails
1. ZERO FULL-HISTORY FORKS: When calling spawn_agent, you MUST ALWAYS set fork_turns = "none". Never use fork_turns = "all" or omit it. Child agents must receive only a compact dispatch contract (<= 1,500 tokens).
2. NO BUSY-POLLING: Never busy-poll wait_agent or repeatedly call list_agents. When waiting for a subagent, wait for reactive notification or use a long timeout (>= 180s).
3. NO MONOLITHIC SUBAGENTS: Do not reuse a subagent across multiple disparate tasks or subsystems. Subagents must own one cohesive slice and terminate upon reporting completion.
4. BOUNDED INSPECTION: Limit sed -n to <= 60 lines. Limit git diff to -U3. Pipe test runs to tail -n 25.

# Repository Invariants & Safety Guardrails
{guardrails_block}

# Adaptive Task Routing (Tiers 0–3)
Classify incoming requests into one of four tiers:
- Tier 0 (Direct Operation): Inspecting status, running deterministic build sync, checking configs -> execute directly without spawning subagents.
- Tier 1 (Surgical Change): 1 file or localized edit, typo, simple helper -> spawn `quick-implementer` with narrow unit check (`{focused_test}`).
- Tier 2 (Cohesive Feature / Localized Bug): 1–3 tightly coupled files in a single subsystem -> spawn `implementer` (owns cohesive seam + unit tests). If public contract or lifecycle changed, spawn `code-reviewer`.
- Tier 3 (Cross-Subsystem / Architectural Change): Multi-subsystem, lifecycle changes, boundary redesign -> spawn `code-explorer` for Discovery Manifest -> spawn `planner` (1–3 cohesive slices) -> spawn `implementer(s)` -> spawn `code-validator` for broad checks (`{full_test}`) -> optional `code-reviewer`.

# Subagent Dispatch & Completion Contracts
Always dispatch subagents with this exact Compact Dispatch Contract:
```markdown
## Assignment
**Goal:** <one sentence>
**Why:** <one or two sentences context>
**Scope:** `path/to/file-a`, `path/to/file-b`
**Relevant symbols:** `symbolA`, `symbolB`
**Verified facts:** <from explorer or previous turn>
**Constraints:** <e.g. preserve dirty worktree, subsystem isolation>
**Required behavior:** <concrete expected result>
**Verification responsibility:** `<exact command the agent must execute>`
**Do not do:** <explicit non-goals>
```
"""

    config_lines = [
        AUTO_GEN_HEADER_TOML,
        "# Root Orchestrator configuration",
        f'model = "{orch.get("model", "gpt-5.6-terra")}"',
        f'model_reasoning_effort = "{orch.get("reasoning_effort", "low")}"',
        f'plan_mode_reasoning_effort = "{orch.get("plan_mode_reasoning_effort", "medium")}"',
        f'tool_output_token_limit = {orch.get("tool_output_token_limit", 2500)}',
        f'model_auto_compact_token_limit = {orch.get("model_auto_compact_token_limit", 45000)}',
        "",
        'developer_instructions = """',
        dev_instructions.strip(),
        '"""',
        "",
        "[features]",
        "multi_agent = true",
        "",
        "[agents]",
        f'default_model = "{orch.get("default_subagent_model", "gpt-5.6-luna")}"',
        f'default_model_reasoning_effort = "{orch.get("default_subagent_reasoning_effort", "low")}"',
        f'max_threads = {orch.get("max_concurrent_threads_per_session", 3)}',
        ""
    ]
    
    agent_files = sorted(list(agents_dir.glob("*.md")))
    for afile in agent_files:
        agent_name = afile.stem
        a_conf = agents_conf.get(agent_name, {})
        desc = a_conf.get("description", f"Specialist agent: {agent_name}")
        model = a_conf.get("model", "gpt-5.6-luna")
        reasoning = a_conf.get("reasoning_effort", "low")
        
        config_lines.append(f"[agents.{agent_name}]")
        config_lines.append(f'description = "{desc}"')
        config_lines.append(f'config_file = "agents/{agent_name}.toml"\n')
        
        with open(afile, "r", encoding="utf-8") as f:
            template_text = f.read()
        compiled_instructions = interpolate_prompt(template_text, project, guardrails_block)
        
        agent_toml_lines = [
            AUTO_GEN_HEADER_TOML,
            f'name = "{agent_name}"',
            f'description = "{desc}"',
            f'model = "{model}"',
            f'model_reasoning_effort = "{reasoning}"'
        ]
        if agent_name == "commit-pusher":
            agent_toml_lines.append('sandbox_mode = "workspace-write"')
            
        agent_toml_lines.append('developer_instructions = """')
        agent_toml_lines.append(compiled_instructions.strip())
        agent_toml_lines.append('"""\n')
        
        outputs[out_agents_dir / f"{agent_name}.toml"] = "\n".join(agent_toml_lines)
        
    outputs[codex_dir / "config.toml"] = "\n".join(config_lines)
    return outputs

def compile_claude(config: dict, project: dict, guardrails_block: str, base_dir: Path, agents_dir: Path) -> dict:
    """Compiles CLAUDE.md. Returns map of file paths to contents."""
    claude_conf = config.get("claude", {})
    orch = claude_conf.get("orchestrator", {})
    agents_conf = claude_conf.get("agents", {})
    
    claude_file = base_dir / "CLAUDE.md"
    
    table_lines = [
        "| Role / Specialist | Target Model | Thinking Effort | Purpose |",
        "| :--- | :--- | :--- | :--- |",
        f"| **Orchestrator (`/root`)** | `{orch.get('model', 'claude-3-7-sonnet')}` | `{orch.get('thinking', 'low')}` | Workflow coordination, routing, cohesive seam scoping |"
    ]
    for aname, aconf in sorted(agents_conf.items()):
        table_lines.append(f"| `{aname}` | `{aconf.get('model', 'claude-3-5-haiku')}` | `{aconf.get('thinking', 'none')}` | Specialist role persona |")
        
    claude_content = f"""{AUTO_GEN_HEADER_MD}
# Claude Code — Project Guidelines & Autonomous Multi-Agent Protocol

## Project Overview: {project.get('name', 'Repository')}
{project.get('description', '')}

---

## 1. Repository Invariants & Safety Guardrails
{guardrails_block}

### Output & Command Bounding Invariants:
- Limit file reads (`sed -n`) to ≤60 lines.
- Limit diff inspection to `git diff -U3` (never use large `-U` ranges).
- Pipe broad test runs or searches to `head -n 30` or `tail -n 25`.
- Never run interactive Git commands (`git add -p`, `git add -i`, `git rebase -i`).

---

## 2. Adaptive Task Routing Policy
Before executing, classify every task into one of four tiers:
- **Tier 0 (Direct Operation)**: Inspecting status, running deterministic build sync, checking small configs → execute directly without ceremony.
- **Tier 1 (Surgical Change)**: 1 file or localized edit, typo, simple helper → execute surgical edit + narrow test.
- **Tier 2 (Cohesive Feature / Localized Bug)**: 1–3 tightly coupled files in a single subsystem → implementer owns complete behavioral seam + focused unit tests.
- **Tier 3 (Cross-Subsystem / Architectural Change)**: Multi-subsystem, lifecycle changes, boundary redesign → plan cohesive slices first, implement sequentially or cleanly partitioned, validate independently.

{ROUTING_ASCII_DIAGRAM}

---

## 3. Specialist Roles & Model Routing Matrix
When assuming specialist personas or delegating subtasks, adhere to the assigned models and thinking budgets:

{chr(10).join(table_lines)}

---

## 4. Specialist Persona Execution Guidelines
Detailed operational rules, fit checks, and circuit breakers for each specialist are maintained in `agents/<name>.md`:
- `agents/code-explorer.md` — Read-only scout; produces structured Discovery Manifests.
- `agents/planner.md` — Contract-oriented slicer (1–3 slices); enforces anti-micro-slicing.
- `agents/implementer.md` — Primary implementer; owns cohesive behavioral seam + unit tests to green.
- `agents/quick-implementer.md` — Low-cost surgical implementer for small, single-file edits.
- `agents/code-validator.md` — Independent runner for broad builds and integration suites (`{project.get('full_test_cmd', 'npm test')}`).
- `agents/code-reviewer.md` — Senior reviewer for semantic risks (lifecycle, concurrency, security).
- `agents/commit-pusher.md` — Safe deterministic non-interactive Git publisher.

When executing as a specialist persona, inspect and adhere strictly to the corresponding template in `agents/`.

---

## 5. Contract-Oriented Cohesive Slicing
- A slice MUST own a complete behavioral contract (state manager + consumer + tests; or client + handler + types).
- NEVER micro-slice by individual functions or separate tests from code.
- Target: 1 slice for localized fixes; 2 slices for moderate features; max 3 slices for separable workstreams.

---

{COMMUNICATION_CONTRACTS_MD}

---

## 6. Validation & Review Policies
- **Validate New Risk, Not Re-Run Proof**: If the implementer verified focused unit tests to green, DO NOT re-run that identical command in `code-validator`. `code-validator` runs ONLY broader suites (`{project.get('full_test_cmd', 'npm test')}`) or builds (`{project.get('build_cmd', 'npm run build')}`).
- **Risk-Based Review**: Invoke `code-reviewer` only for semantic risk (state machine, concurrency, boundaries, security, storage migrations, public contracts). Skip for pure DOM/CSS, presentation, formatting, or low-risk mechanical changes.
"""
    outputs = {claude_file: claude_content}
    for afile in sorted(agents_dir.glob("*.md")):
        name = afile.stem
        agent = agents_conf.get(name, {})
        description = agent.get("description", f"Specialist agent: {name}")
        body = interpolate_prompt(afile.read_text(encoding="utf-8"), project, guardrails_block)
        frontmatter = ["---", f"name: {name}", f"description: {json.dumps(description)}"]
        if agent.get("model"):
            frontmatter.append(f"model: {agent['model']}")
        frontmatter.extend(["---", ""])
        outputs[base_dir / ".claude" / "agents" / f"{name}.md"] = "\n".join(frontmatter) + body
    return outputs

def compile_gemini(config: dict, project: dict, guardrails_block: str, base_dir: Path) -> dict:
    """Compile Gemini CLI's project context and settings files."""
    gemini_conf = config.get("gemini", {})
    orch = gemini_conf.get("orchestrator", {})
    agents_conf = gemini_conf.get("agents", {})
    
    gemini_file = base_dir / "GEMINI.md"
    
    table_lines = [
        "| Subagent Role | Model Tier (`invoke_subagent`) | Purpose |",
        "| :--- | :--- | :--- |",
        f"| **Orchestrator (`/root`)** | `{orch.get('model', 'pro')}` | Intent interpretation, routing, cohesive seam scoping |"
    ]
    for aname, aconf in sorted(agents_conf.items()):
        table_lines.append(f"| `{aname}` | `{aconf.get('model', 'flash')}` | Specialist persona execution |")
        
    agents_content = f"""{AUTO_GEN_HEADER_MD}
# Autonomous Multi-Agent Protocol — {project.get('name', 'Repository')}

**Charter:** The `/root` Orchestrator coordinates workflow for {project.get('name', 'this repository')} ({project.get('description', '')}). `/root` owns intent interpretation, task classification, routing, cohesive slicing, synthesis, and completion decisions. Specialized agents own planning, exploration, implementation, verification, review, and Git publishing.

The primary optimization metric is:
**Total resources required to reach a correct, validated, shippable result.**
Avoid premature multi-agent ceremonies: use one capable owner by default, and spawn specialists only when they contribute new information, independent work, or independent evidence.

---

## 1. Repository Invariants & Safety Guardrails
{guardrails_block}

### Universal Operational Invariants:
- **Subsystem Isolation**: Never combine disjoint subsystems in one implementation slice.
- **Generated Assets Rule**: Never spawn an LLM agent to copy, diff, or patch generated build assets. Use deterministic build commands (`{project.get('build_sync_cmd', 'npm run build')}`).
- **Strictly Non-Interactive Git**: Agents must never run interactive Git commands (`git add -p`, `git add -i`, `git rebase -i`).
- **Zero Full-History Forks (`fork_turns = "none"`)**: Subagents must NEVER be spawned with full parent history. Child subagents receive only the Compact Dispatch Contract (≤ 1,500 tokens).
- **Anti-Polling Invariant**: Never busy-poll or loop waiting for agents; rely on reactive wakeups or long timeouts (≥ 180s).
- **Command Output Bounds**: Limit file reads (`sed -n`) to ≤60 lines. Limit `git diff` to `-U3`. Pipe broad test outputs to `tail -n 25`.
- **Circuit Breakers**:
  * *Implementer Failure Breaker:* Stop immediately after 2 failed attempts on the same issue; report blocker to `/root`.
  * *Tool-Loop Ceilings:*
    - `/root` Orchestrator: hard ceiling of 25 turns per task.
    - Standard agents (`explorer`, `implementer`): soft warning at 10–12 tool calls, hard ceiling at 16–20.
    - Mechanical (`quick-implementer`): hard ceiling at 8.
    - Publishing (`commit-pusher`): hard maximum of 6 tool calls.

---

## 2. Adaptive Task Routing

`/root` classifies each incoming request into one of four tiers:

{ROUTING_ASCII_DIAGRAM}

### Tier 0 — Direct Orchestrator Task
- **When:** Inspecting Git status, running asset sync, checking configs.
- **Workflow:** `/root` executes directly in workspace without subagents.

### Tier 1 — Surgical Change
- **When:** 1 file or tightly localized edit; typos, simple helpers, isolated bug fixes.
- **Workflow:** `quick-implementer` → runs focused unit check (`{project.get('focused_test_cmd', 'npm test -- {file}')}`) → complete.
- **Rules:** No planner, no explorer, no validator by default.

### Tier 2 — Cohesive Feature or Localized Bug
- **When:** 1–3 tightly coupled files in a single subsystem; bug with known reproduction.
- **Workflow:** `implementer` (owns cohesive seam + unit tests) → optional `code-reviewer` (if public contract/lifecycle changed).

### Tier 3 — Cross-Subsystem / Architectural Change
- **When:** Multiple subsystems, lifecycle/state changes, inter-service boundary redesign, high regression risk.
- **Workflow:** `code-explorer` → `planner` (1–3 cohesive slices) → `implementer(s)` → `code-validator` → optional `code-reviewer`.

---

## 3. Gemini / Antigravity Model & Dispatch Protocol

### Subagent Dispatch Convention:
When invoking subagents via `invoke_subagent`:
1. Use `TypeName: "self"` (or `TypeName: "research"` for read-only exploration).
2. Set `Role: "<agent-role>"` (e.g. `Role: "code-explorer"`, `Role: "implementer"`).
3. Set `Model` according to the matrix below (`flash` or `pro`).
4. In the `Prompt`, include the **Compact Dispatch Contract** and instruct the subagent to adopt the persona guidelines defined in `agents/<name>.md`.

{chr(10).join(table_lines)}

---

## 4. Inter-Agent Communication Contracts

{COMMUNICATION_CONTRACTS_MD}

---

## 5. Validation & Review Policies

- **Validate New Risk, Not Re-Run Proof**: If the implementer verified focused unit tests to green, DO NOT re-run that command in `code-validator`. `code-validator` runs ONLY broader suites (`{project.get('full_test_cmd', 'npm test')}`) or builds (`{project.get('build_cmd', 'npm run build')}`).
- **Risk-Based Review**: Invoke `code-reviewer` only for semantic risk (state machine, concurrency, boundaries, security, storage migrations, public contracts). Skip for pure DOM/CSS, presentation, formatting, or low-risk mechanical changes.
"""
    settings = json.dumps({"_generated": "AUTO-GENERATED BY sync.py",
                           "context": {"fileName": "GEMINI.md"}}, indent=2) + "\n"
    return {gemini_file: agents_content, base_dir / ".gemini" / "settings.json": settings}

def compile_antigravity(config: dict, project: dict, guardrails_block: str, base_dir: Path) -> dict:
    """Conservative Antigravity target: portable repository instructions only."""
    gemini = compile_gemini(config, project, guardrails_block, base_dir)
    return {base_dir / "AGENTS.md": gemini[base_dir / "GEMINI.md"]}

def detect_project_stack(target_dir: Path) -> dict:
    """
    Inspects target_dir and detects project stack, build/test commands, and forbidden paths.
    Returns a dictionary suitable for generating config.toml.
    """
    project_name = target_dir.resolve().name
    
    # 1. Check Node / TypeScript / JavaScript
    pkg_json_path = target_dir / "package.json"
    if pkg_json_path.exists():
        try:
            with open(pkg_json_path, "r", encoding="utf-8") as f:
                pkg_data = json.load(f)
        except Exception:
            pkg_data = {}
            
        desc = pkg_data.get("description") or "Node.js application"
        scripts = pkg_data.get("scripts", {})
        
        # Package manager detection
        if (target_dir / "pnpm-lock.yaml").exists():
            pm = "pnpm"
        elif (target_dir / "yarn.lock").exists():
            pm = "yarn"
        elif (target_dir / "bun.lockb").exists() or (target_dir / "bun.lock").exists():
            pm = "bun"
        else:
            pm = "npm"
            
        has_build = "build" in scripts
        has_test = "test" in scripts
        has_int_test = any(k in scripts for k in ["test:integration", "test:e2e", "integration", "test:all"])
        
        return {
            "name": project_name,
            "description": desc,
            "stack": "Node.js",
            "forbidden_paths": ["dist/**", "build/**", "coverage/**", "node_modules/**"],
            "build_sync_cmd": f"{pm} run build" if has_build else "",
            "focused_test_cmd": f"{pm} test -- {{file}}" if has_test else f"{pm} test",
            "full_test_cmd": f"{pm} run test:integration" if has_int_test else (f"{pm} test" if has_test else ""),
            "build_cmd": f"{pm} run build" if has_build else "",
            "subsystems": []
        }
        
    # 2. Check Rust
    cargo_path = target_dir / "Cargo.toml"
    if cargo_path.exists():
        return {
            "name": project_name,
            "description": "Rust application",
            "stack": "Rust",
            "forbidden_paths": ["target/**"],
            "build_sync_cmd": "cargo build",
            "focused_test_cmd": "cargo test -- {test_name}",
            "full_test_cmd": "cargo test",
            "build_cmd": "cargo build",
            "subsystems": []
        }

    # 3. Check Go
    go_mod_path = target_dir / "go.mod"
    if go_mod_path.exists():
        return {
            "name": project_name,
            "description": "Go application",
            "stack": "Go",
            "forbidden_paths": ["bin/**", "vendor/**"],
            "build_sync_cmd": "go build ./...",
            "focused_test_cmd": "go test -run {test_name} ./...",
            "full_test_cmd": "go test ./...",
            "build_cmd": "go build ./...",
            "subsystems": []
        }

    # 4. Check Python
    is_python = any((target_dir / p).exists() for p in [
        "pyproject.toml", "requirements.txt", "setup.py", "pytest.ini", "tox.ini"
    ]) or list(target_dir.glob("*.py"))
    
    if is_python:
        has_pytest = (target_dir / "pytest.ini").exists() or (target_dir / "tests").exists() or (target_dir / "test").exists()
        focused_cmd = "python3 -m pytest {file}" if has_pytest else "python3 -m unittest {file}"
        full_cmd = "pytest" if has_pytest else "python3 -m unittest discover tests"
        
        return {
            "name": project_name,
            "description": "Python application",
            "stack": "Python",
            "forbidden_paths": [".git/**", "__pycache__/**", "dist/**", "build/**", ".venv/**", ".pytest_cache/**"],
            "build_sync_cmd": "",
            "focused_test_cmd": focused_cmd,
            "full_test_cmd": full_cmd,
            "build_cmd": "python3 -m compileall .",
            "subsystems": []
        }

    # 5. Default generic fallback
    return {
        "name": project_name,
        "description": "Software project",
        "stack": "Generic",
        "forbidden_paths": ["dist/**", "build/**", ".cache/**"],
        "build_sync_cmd": "",
        "focused_test_cmd": "make test",
        "full_test_cmd": "make test",
        "build_cmd": "make build",
        "subsystems": []
    }

def generate_default_config_toml(stack_info: dict) -> str:
    """Generates standard config.toml content pre-populated with detected stack information."""
    forbidden_toml = ",\n  ".join([f'"{p}"' for p in stack_info.get("forbidden_paths", [])])
    
    return f"""# ==============================================================================
# AUTONOMOUS AGENT PROTOCOL CONFIGURATION
# Single source of truth for repository invariants and multi-provider models.
# Edit this file, then run `./sync.py` to regenerate provider-specific configs.
# ==============================================================================

active_provider = "all"  # "all" | "codex" | "claude" | "gemini" | "antigravity"

[schema]
name = "autonomous-dev-team"
version = 1

# ==============================================================================
# PROJECT INVARIANTS (Compiled into agent instructions to prevent hallucinations)
# ==============================================================================
[project]
name = "{stack_info.get('name', 'project')}"
description = "{stack_info.get('description', 'Autonomous Multi-Agent Repository')}"

# Paths that agents are strictly forbidden from editing, copying, or diffing directly.
forbidden_paths = [
  {forbidden_toml}
]

# Command to deterministically synchronize/build generated assets (replaces LLM asset editing).
build_sync_cmd = "{stack_info.get('build_sync_cmd', '')}"

# Focused unit test command template.
# Agents interpolate {{file}} or {{test_name}} for narrow verification before handoff.
focused_test_cmd = "{stack_info.get('focused_test_cmd', 'npm test -- {file}')}"

# Broad verification suite command executed ONLY by code-validator when new risk is introduced.
full_test_cmd = "{stack_info.get('full_test_cmd', 'npm test')}"

# Build / compilation verification command (owned by code-validator).
build_cmd = "{stack_info.get('build_cmd', '')}"

# Subsystems to enforce strict architectural isolation (optional).
# [[project.subsystems]]
# name = "core"
# path = "src/core/"
# stack = "{stack_info.get('stack', 'Core')}"


# ==============================================================================
# OPENAI / CODEX CONFIGURATION
# Generates .codex/config.toml and .codex/agents/*.toml
# ==============================================================================
[codex.orchestrator]
model = "gpt-5.6-terra"
reasoning_effort = "low"
plan_mode_reasoning_effort = "medium"
default_subagent_model = "gpt-5.6-luna"
default_subagent_reasoning_effort = "low"
max_concurrent_threads_per_session = 3
tool_output_token_limit = 2500
model_auto_compact_token_limit = 45000

[codex.agents.code-explorer]
description = "Read-only repository scout for targeted discovery, producing structured Discovery Manifests."
model = "gpt-5.6-luna"
reasoning_effort = "low"

[codex.agents.planner]
description = "Repository-grounded engineering planner used ONLY for Tier 3 complex, architectural, or multi-subsystem changes."
model = "gpt-5.6-sol"
reasoning_effort = "low"

[codex.agents.quick-implementer]
description = "Low-cost surgical implementer for small, mechanical, single-file, low-risk edits."
model = "gpt-5.6-luna"
reasoning_effort = "low"

[codex.agents.implementer]
description = "Primary implementer for substantive features, owning complete behavioral seams and verifying unit tests to green."
model = "gpt-5.6-sol"
reasoning_effort = "low"

[codex.agents.code-validator]
description = "Independent verification runner for broad builds, integration suites, and cross-module checks. Validates new risk."
model = "gpt-5.6-luna"
reasoning_effort = "low"

[codex.agents.code-reviewer]
description = "Independent senior reviewer for high-risk diffs (lifecycle, concurrency, native bridges, public contracts, security)."
model = "gpt-5.6-terra"
reasoning_effort = "low"

[codex.agents.commit-pusher]
description = "Deterministic Git publishing agent used only after an explicit user request. Non-interactive path staging."
model = "gpt-5.6-luna"
reasoning_effort = "low"


# ==============================================================================
# ANTHROPIC / CLAUDE CODE CONFIGURATION
# Generates CLAUDE.md with project guardrails and model routing guidance
# ==============================================================================
[claude.orchestrator]
model = "claude-3-7-sonnet"
thinking = "low"

[claude.agents.code-explorer]
model = "claude-3-5-haiku"
thinking = "none"

[claude.agents.planner]
model = "claude-3-7-sonnet"
thinking = "high"

[claude.agents.quick-implementer]
model = "claude-3-5-haiku"
thinking = "none"

[claude.agents.implementer]
model = "claude-3-7-sonnet"
thinking = "medium"

[claude.agents.code-validator]
model = "claude-3-5-haiku"
thinking = "none"

[claude.agents.code-reviewer]
model = "claude-3-7-sonnet"
thinking = "high"

[claude.agents.commit-pusher]
model = "claude-3-5-haiku"
thinking = "none"


# ==============================================================================
# GOOGLE / GEMINI (ANTIGRAVITY / AGY) CONFIGURATION
# Generates AGENTS.md & GEMINI.md with subagent tier enums (inherit, flash, flash_lite, pro)
# ==============================================================================
[gemini.orchestrator]
model = "pro"
reasoning = "low"

[gemini.agents.code-explorer]
model = "flash"

[gemini.agents.planner]
model = "pro"

[gemini.agents.quick-implementer]
model = "flash"

[gemini.agents.implementer]
model = "pro"

[gemini.agents.code-validator]
model = "flash"

[gemini.agents.code-reviewer]
model = "pro"

[gemini.agents.commit-pusher]
model = "flash"
"""

def generate_all_outputs(base_dir: Path, provider_override: str = None) -> dict:
    """Generates a dict of Path -> content for all target provider files without writing them to disk."""
    config_path = resolve_config_path(base_dir)
    agents_dir = base_dir / "agents"
    config = load_config(config_path)
    project = config.get("project", {})
    provider = provider_override or config.get("active_provider", "all")
    
    guardrails_block = build_project_guardrails(project)
    
    all_outputs = {}
    if provider in ("all", "codex"):
        all_outputs.update(compile_codex(config, project, guardrails_block, base_dir, agents_dir))
    if provider in ("all", "claude"):
        all_outputs.update(compile_claude(config, project, guardrails_block, base_dir, agents_dir))
    if provider in ("all", "gemini"):
        all_outputs.update(compile_gemini(config, project, guardrails_block, base_dir))
    if provider in ("all", "antigravity", "agy"):
        all_outputs.update(compile_antigravity(config, project, guardrails_block, base_dir))
        
    return all_outputs

def run_sync(base_dir: Path, provider_override: str = None):
    print("Synchronizing Multi-Provider Autonomous Agent Protocol...")
    outputs = generate_all_outputs(base_dir, provider_override)
    manifest_path = base_dir / MANIFEST_NAME
    previous = []
    if manifest_path.exists():
        try:
            previous = json.loads(manifest_path.read_text(encoding="utf-8")).get("files", [])
        except (OSError, ValueError, TypeError):
            previous = []
    current = {str(path.relative_to(base_dir)) for path in outputs}
    scope = provider_scope(base_dir, provider_override)
    preserved = set() if scope == "all" else {
        path for path in previous if output_provider(path) != scope
    }
    for relative in sorted(set(previous) - current - preserved):
        stale = managed_path(base_dir, relative)
        if stale and stale.is_file() and "AUTO-GENERATED BY sync.py" in stale.read_text(encoding="utf-8"):
            stale.unlink()
    
    codex_count = 0
    claude_updated = False
    gemini_updated = False
    antigravity_updated = False
    
    for fpath, content in outputs.items():
        fpath.parent.mkdir(parents=True, exist_ok=True)
        with open(fpath, "w", encoding="utf-8") as f:
            f.write(content)
        if ".codex" in str(fpath):
            codex_count += 1
        elif fpath.name == "CLAUDE.md":
            claude_updated = True
        elif fpath.name == "GEMINI.md":
            gemini_updated = True
        elif fpath.name == "AGENTS.md":
            antigravity_updated = True
    manifest_path.write_text(json.dumps({"schema": SCHEMA_NAME, "version": SCHEMA_VERSION,
                                         "files": sorted(current | preserved)}, indent=2) + "\n", encoding="utf-8")
            
    if codex_count > 0:
        print(f"  ✓ Codex: Compiled {codex_count - 1} agents into .codex/")
    if claude_updated:
        print("  ✓ Claude Code: Generated CLAUDE.md")
    if gemini_updated:
        print("  ✓ Gemini CLI: Generated GEMINI.md and .gemini/settings.json")
    if antigravity_updated:
        print("  ✓ Antigravity: Generated conservative AGENTS.md guidance")
        
    print("✓ Synchronization complete.\n")

def run_check(base_dir: Path, provider_override: str = None) -> int:
    """Checks generated files and their ownership manifest. Returns 0 if matching."""
    outputs = generate_all_outputs(base_dir, provider_override)
    mismatched = []
    missing = []
    stale = []
    
    for fpath, expected_content in outputs.items():
        if not fpath.exists():
            missing.append(fpath.relative_to(base_dir))
        else:
            with open(fpath, "r", encoding="utf-8") as f:
                actual_content = f.read()
            if actual_content != expected_content:
                mismatched.append(fpath.relative_to(base_dir))
    manifest_path = base_dir / MANIFEST_NAME
    if not manifest_path.exists():
        missing.append(Path(MANIFEST_NAME))
    else:
        try:
            owned = json.loads(manifest_path.read_text(encoding="utf-8")).get("files", [])
        except (OSError, ValueError, TypeError):
            owned = []
        expected = {str(path.relative_to(base_dir)) for path in outputs}
        scope = provider_scope(base_dir, provider_override)
        stale = [Path(path) for path in owned
                 if path not in expected and (scope == "all" or output_provider(path) == scope)
                 and managed_path(base_dir, path)
                 and managed_path(base_dir, path).exists()]
                
    if not missing and not mismatched and not stale:
        print(f"✓ All provider configurations are in sync with {CONFIG_NAME} and agents/.")
        return 0
    else:
        print("Error: Provider configurations are out of sync!")
        if missing:
            print("  Missing files:")
            for m in missing:
                print(f"    - {m}")
        if mismatched:
            print("  Out-of-date files:")
            for m in mismatched:
                print(f"    - {m}")
        if stale:
            print("  Stale managed files:")
            for item in stale:
                print(f"    - {item}")
        print("\nRun './sync.py' to regenerate provider files.")
        return 1

def run_init(target_dir: Path, provider_override: str = None):
    """Initializes the namespaced config if missing, then compiles provider files."""
    config_path = target_dir / CONFIG_NAME
    print(f"Initializing Autonomous Multi-Agent Protocol in: {target_dir.resolve()}")
    
    legacy_path = target_dir / LEGACY_CONFIG_NAME
    if not config_path.exists() and legacy_path.exists() and is_legacy_config(load_config(legacy_path)):
        legacy_content = legacy_path.read_text(encoding="utf-8").rstrip()
        schema = (f'\n\n[schema]\nname = "{SCHEMA_NAME}"\n'
                  f'version = {SCHEMA_VERSION}\n')
        config_path.write_text(legacy_content + schema, encoding="utf-8")
        print(f"  ✓ Migrated legacy {LEGACY_CONFIG_NAME} to {CONFIG_NAME}; legacy file preserved.")
    if config_path.exists():
        print(f"  ℹ Existing {CONFIG_NAME} found in {target_dir.resolve()}. Preserving settings.")
    else:
        print("  🔍 Detecting project stack...")
        stack_info = detect_project_stack(target_dir)
        print(f"  ✓ Detected stack: {stack_info.get('stack')} ({stack_info.get('name')})")
        if stack_info.get("focused_test_cmd"):
            print(f"    - Test command: {stack_info.get('focused_test_cmd')}")
        if stack_info.get("build_cmd"):
            print(f"    - Build command: {stack_info.get('build_cmd')}")
            
        config_content = generate_default_config_toml(stack_info)
        with open(config_path, "w", encoding="utf-8") as f:
            f.write(config_content)
        print(f"  ✓ Generated tailored {CONFIG_NAME} for {stack_info.get('name')}")
        
    run_sync(target_dir, provider_override)

def main():
    parser = argparse.ArgumentParser(description="Autonomous Multi-Agent Protocol — Synchronizer & Compiler")
    parser.add_argument("--init", nargs="?", const=".", default=None, metavar="DIR",
                        help=f"Initialize {CONFIG_NAME} with auto-detected stack in target directory (defaults to current dir) and compile.")
    parser.add_argument("--check", action="store_true",
                        help=f"Check whether generated provider files are in sync with {CONFIG_NAME} (exits with 0 if up-to-date, 1 if out-of-sync).")
    parser.add_argument("--provider", choices=["all", "codex", "claude", "gemini", "antigravity", "agy"], default=None,
                        help="Override active provider.")
    parser.add_argument("--dir", default=None, metavar="DIR",
                        help=f"Directory containing {CONFIG_NAME} and agents/ (defaults to script directory).")

    args = parser.parse_args()

    base_dir = Path(args.dir).resolve() if args.dir else Path(__file__).resolve().parent

    if args.init is not None:
        target_dir = Path(args.init).resolve()
        run_init(target_dir, args.provider)
    elif args.check:
        sys.exit(run_check(base_dir, args.provider))
    else:
        run_sync(base_dir, args.provider)

if __name__ == "__main__":
    main()
